### ISSUE TITLE
Error 500.30 at runtime (publish time) on version 6.4.0

### ISSUE THREAD

**Issue by amin720** [domaindrivendev/Swashbuckle.AspNetCore#2523] opened 2022-10-22 09:59 UTC
hi
I recently updated to version 6.4.0, but the runtime gives an error of 500.30 in the publish?!
Windows server specifications:
windows server 2016
microsoft net core runtime v6.0.10
microsoft net core sdk v6.0.402

**Comment by domaindrivendev** [comment] 2022-11-15 23:46
I can't possible help with such little information. Please provide clear repro steps as per the [issue guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/ISSUE_TEMPLATE.md)

**Comment by Rubenisme** [comment] 2022-12-06 14:00
I also have this after upgrading to .NET 7, this resulted in

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Swashbuckle.AspNetCore.Annotations, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

The stacktrace indicates that this happens at time of calling AddControllers in my code.

We had trimming on `<PublishTrimmed>true</PublishTrimmed>` with copyused mode `<TrimMode>copyused</TrimMode>`.

And these 2 packages:
`<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />`
`<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.4.0" />`

After turning trimming off, things worked fine again. For some reason this was not an issue in .NET 6 with the same package versions.

**Comment by Havunen** [comment] 2024-03-05 19:28
I believe this is fixed in DotSwashbuckle

**Comment by martincostello** [comment] 2024-04-14 11:19
Duplicate of #2550

**Closed by martincostello** 2024-04-14 11:19 UTC
Labels: responded
