### ISSUE TITLE
[5.0.0] AllOf in Properties Breaking Back Compat

### ISSUE THREAD

**Issue by matthawley** [domaindrivendev/Swashbuckle.AspNetCore#1488] opened 2020-01-16 19:41 UTC
Swagger Version: v2

While I realize that having AllOf for properties is valid for swagger, making this change from RC5 -> official release did not provide time for people to comment and it's causing backwards compatibility issues with multiple of our components that do not handle AllOf appropriately. This is blocking us from moving from RC5.

Can I request that this be opt-in (or now that 5.0.0 is released, opt-out)? All other new references of AllOf were added behind the Polymorphic check, which is disabled by default.

Specifically, I'm referring to this line:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/f987e3613fa9d3a34695d70a40c85f3c7d65f294/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftObjectHandler.cs#L146

**Comment by matthawley** [comment] 2020-01-16 20:16
I wrote a filter to reverse this change.

```
public class ReverseAllOfPropertiesFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        (string key, OpenApiSchema typeSchema)[] allOfProperties = schema.Properties
            .Where(x => null != x.Value.AllOf && 1 == x.Value.AllOf.Count)
            .Select(x => (x.Key, x.Value.AllOf.First()))
            .ToArray();

        foreach ((string key, OpenApiSchema typeSchema) item in allOfProperties)
        {
            schema.Properties[item.key] = item.typeSchema;
        }
    }
}
```

**Comment by domaindrivendev** [comment] 2020-01-17 16:36
While I think it's reasonable to introduce breaking changes for folks who are depending on pre-release versions (it's one of the caveats to using pre-release software), I do agree that this should be an optional setting.

This changed was introduced to address the issue described [here](https://github.com/OAI/OpenAPI-Specification/issues/1368), specifically that contextual metadata (e.g. a property description, whether a property can have a null value etc.) cannot be assigned to referenced schema's because the same schema may be used in different contexts where the contextual metadata may not always apply.

While the introduction of an inline schema that "extends" a shared schema (via `allOf`) for certain properties is a little ugly, it is perfectly valid and it's also the recommended approach to workaround this glaring constraint in the specification. So, based on that, I'm leaning toward an opt-out setting. Does that seem like the right call to you?

**Comment by matthawley** [comment] 2020-01-17 17:32
Totally reasonable to have breaking changes, it was just unexpected between the last RC and the release.

I'm good with the opt-out approach.

**Comment by kant2002** [comment] 2020-02-03 13:51
@domaindrivendev the additional problem here is that AutoRest breaks when using `allOf`. I understand that strictly speaking this is not issue of Swashbuckle, but it create inconvenience for these who use Swashbuclke + Autorest. I'm also fine with current solution, given that it is presented here. If you know where in the docs that can be highlighted, I can submit PR to docs.

**Comment by scp-mb** [comment] 2020-02-10 12:06
This has also hit us for one of our APIs, it's no longer specifying the correct classes on properties, or even nested properties which causes Autorest to create it's own intermediate classes. Using the SchemaFilter above from @matthawley does restore the expected behaviour.

5.0.0-rc5:
![image](https://user-images.githubusercontent.com/52526733/74148065-77aeaf00-4bfc-11ea-9225-5be22c68c83c.png)
![image](https://user-images.githubusercontent.com/52526733/74148278-04f20380-4bfd-11ea-8903-2c3957c77f06.png)

5.0.0:
![image](https://user-images.githubusercontent.com/52526733/74148364-2f43c100-4bfd-11ea-8ec1-b28fe77d8404.png)
![image](https://user-images.githubusercontent.com/52526733/74148462-61edb980-4bfd-11ea-947a-fd3c46ab08c4.png)

**Comment by markusschaber** [comment] 2020-02-17 17:59
This also hit us, our app build broke. :-/

**Comment by tmarkovski** [comment] 2020-03-01 15:45
This completely breaks pipelines depending on Swashbuckle + Autorest to generate service clients
https://github.com/Azure/autorest/issues/3417

**Closed** 2020-03-05 21:46 UTC

**Comment by domaindrivendev** [comment] 2020-03-11 14:19
As of 5.1.0, the `allOf` behavior has been made opt-in. This should resolve backcompat issues. For anyone wanting this behavior going forward, please use the following setting `UseAllOfToExtendReferenceSchemas`.

**Comment by SkinnySackboy** [comment] 2020-03-26 21:09
@markusschaber @tmarkovski @kant2002 have any of you managed to find a suitable solution to this allOf issue between Swashbuckle and Autorest? I've been trying for a few days, using workarounds to suppress/remove the allOf etc. from the json but I simply cannot get it to work, having recently upgraded from ASP.NET Core 2.2 to 3.1 and from Swashbuckle 4.0.1 to 5.1.2

Thanks!

**Comment by matthawley** [comment] 2020-03-26 21:14
@SkinnySackboy Per @domaindrivendev an opt-out was added in 5.1.0.

**Comment by kant2002** [comment] 2020-03-26 21:21
@SkinnySackboy I just use class posted here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1488#issuecomment-575327707

**Comment by SkinnySackboy** [comment] 2020-03-26 21:41
Thanks @matthawley do you know how I can opt-out?

@kant2002 Thanks, I tried this but it doesn't seem to help unfortunately, I still have json created with allOf which AutoRest doesn't like.

**Comment by matthawley** [comment] 2020-03-26 21:43
@SkinnySackboy We haven't taken a newer version yet, so I can't really help other than saying my original filter does work for us. Just make sure you're registering it.

**Comment by SkinnySackboy** [comment] 2020-03-26 21:52
Thanks @matthawley I'll try again perhaps with older versions and see if some other combination than what I'm trying works.

**Comment by markusschaber** [comment] 2020-03-30 06:42
@SkinnySackboy we're using some post processing/filtering of the Json. I don't know the exact details, as another team member implemented it.

**Comment by SkinnySackboy** [comment] 2020-03-30 07:30
@markusschaber Many thanks, I ended up doing something similar.
