### ISSUE TITLE
V5.0.0-RC3 build error with ASP.Net Core 3.0

### ISSUE THREAD

**Issue by juan-carlos-diaz** [domaindrivendev/Swashbuckle.AspNetCore#1281] opened 2019-09-28 14:46 UTC
Versions:
   Swashbuckle.AspNetCore 5.0.0-rc3
   ASP.Net Core 3.0
   Visual Studio 2019 16.3.1

Repro steps:
1- Create new 'ASP.Net Core Web Application' project
    Be sure to select:
    1.1 .Net Core
    1.2 ASP.NET Core 3.0
    1.3 API
2- Install Swashbuckle.AspNetCore 5.0.0-rc3
3- Build, get the following error:
Error	MSB3073	The command "dotnet "C:\Users\XXXXX\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "C:\Users\XXXXX\source\repos\WebApplication2\WebApplication2\bin\Debug\netcoreapp3.0\WebApplication2.dll" --file-list "obj\WebApplication2.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "WebApplication2" --assets-file "C:\Users\XXXXX\source\repos\WebApplication2\WebApplication2\obj\project.assets.json" --platform "AnyCPU" " exited with code 6.	WebApplication2	C:\Users\XXXXX\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\Microsoft.Extensions.ApiDescription.Server.targets	41

**Comment by jackbond** [comment] 2019-09-28 14:56
I don't know when the next build will be available, but downgrading to RC2 made the build error go away for me.

**Comment by juan-carlos-diaz** [comment] 2019-09-28 15:02
Thanks!!!
Now waiting for the final release

**Comment by vitalybibikov** [comment] 2019-09-28 15:14
I have this error only for 1 micro-service out of 17. 

Can't share the source code, unfortunately, but only it's stacktrace.
if it's not enough, I will try to create a reprow

Error	MSB3073	The command "dotnet "C:\Users\xxx\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "C:\xxx\bin\Debug\netcoreapp3.0\xxx.dll" --file-list "obj\xxx.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "xxx" --assets-file "C:\xxx\obj\project.assets.json" --platform "AnyCPU" " exited with code 7.	xxx	C:\Users\xxx\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\Microsoft.Extensions.ApiDescription.Server.targets	41	



The stack is:

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
23> ---> System.InvalidOperationException: Can't use schemaId "$XXXAnswerType" for type "xxxQueries.Contracts.Enums.XXXVcioAnswerType". The same schemaId is already used for type "xxx.Common.Enums.ReviewVcioAnswerType"
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.ReserveIdFor(Type type, String schemaId)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiObjectHandler.GeneratePropertySchema(ApiProperty apiObjectProperty, IEnumerable`1 memberAttributes, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiObjectHandler.GenerateDefinitionSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateDefinitionSchemaAndApplyFilters(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.<>c__DisplayClass11_0.<GenerateSchema>b__0()
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiArrayHandler.GenerateDefinitionSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateDefinitionSchemaAndApplyFilters(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiObjectHandler.GeneratePropertySchema(ApiProperty apiObjectProperty, IEnumerable`1 memberAttributes, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiObjectHandler.GenerateDefinitionSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateDefinitionSchemaAndApplyFilters(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.<>c__DisplayClass11_0.<GenerateSchema>b__0()
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiArrayHandler.GenerateDefinitionSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateDefinitionSchemaAndApplyFilters(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiObjectHandler.GeneratePropertySchema(ApiProperty apiObjectProperty, IEnumerable`1 memberAttributes, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiObjectHandler.GenerateDefinitionSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateDefinitionSchemaAndApplyFilters(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.<>c__DisplayClass11_0.<GenerateSchema>b__0()
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass19_0.<GenerateResponse>b__2(String contentType)
23>   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
23>   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
23>   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
23>   at Microsoft.Extensions.ApiDescriptions.DocumentProvider.GenerateAsync(String documentName, TextWriter writer)
23>   --- End of inner exception stack trace ---
23>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
23>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
23>   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
23>   at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.InvokeMethod(MethodInfo method, Object instance, Object[] arguments)
23>   at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.GetDocument(String documentName, String projectName, String outputDirectory, MethodInfo generateMethod, Object service)
23>   at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.GetDocuments(GetDocumentCommandContext context, IServiceProvider services)
23>   at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.Process(GetDocumentCommandContext context)`

**Comment by jackbond** [comment] 2019-09-28 15:27
FYI guys, this thread is a duplicate of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1266

**Comment by vitalybibikov** [comment] 2019-09-28 15:30
Can confirm, that downgrading to rc2 solves the issue

**Closed** 2019-09-28 23:12 UTC
