### ISSUE TITLE
ASP.NET Core WebAPI - .NET 7: Swagger UI is empty, but still have HTML source

### ISSUE THREAD

**Issue by donhuvy** [domaindrivendev/Swashbuckle.AspNetCore#2572] opened 2022-12-11 14:19 UTC
[ASP.NET Core WebAPI - .NET 7: Swagger UI is empty, but still have HTML source](https://stackoverflow.com/questions/74761184/asp-net-core-webapi-net-7-swagger-ui-is-empty-but-still-have-html-source)

Upgrade source code from .NET 6 at here https://github.com/PacktPublishing/Ultimate-ASP.NET-5-Web-API-Development-Guide-/tree/main/Section%209/HotelListing.API to .NET 7. Then Swagger did not show.

https://stackoverflow.com/questions/74761184/asp-net-core-webapi-net-7-swagger-ui-is-empty-but-still-have-html-source

**Comment by martincostello** [comment] 2024-04-14 10:54
Duplicate of #2290

**Closed by martincostello** 2024-04-14 10:54 UTC
