### ISSUE TITLE
Array of nullable type do not set Nullable=true in generated open api

### ISSUE THREAD

**Issue by worming004** [domaindrivendev/Swashbuckle.AspNetCore#2628] opened 2023-04-07 11:11 UTC
As this test expose https://github.com/worming004/Swashbuckle.AspNetCore/commit/3506ff1ff614579af70ade83be4aff93d90bceb9

```
[Theory]
[InlineData(typeof(int?[]), "integer", "int32", true)]
public void GenerateSchema_GeneratesArraySchema_IfEnumerableType(
    Type type,
    string expectedItemsType,
    string expectedItemsFormat,
    bool expectedItemsNullable)
{
    var schema = Subject().GenerateSchema(type, new SchemaRepository());

    Assert.Equal("array", schema.Type);
    Assert.NotNull(schema.Items);
    Assert.Equal(expectedItemsType, schema.Items.Type);
    Assert.Equal(expectedItemsFormat, schema.Items.Format);
    Assert.Equal(expectedItemsNullable, schema.Items.Nullable); // test fail here
}
```

The array's item is not set to nullable. Item is expected to be nullable because input type is `int?`

**Comment by 304NotModified** [comment] 2023-08-25 22:38
Is this https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2059?

**Comment by worming004** [comment] 2023-08-28 15:51
Yes it is

**Comment by martincostello** [comment] 2024-04-14 09:42
Duplicate of #2059.

**Closed by martincostello** 2024-04-14 09:42 UTC
