### ISSUE TITLE
CLI: configuration from appsettings.json is not loaded

### ISSUE THREAD

**Issue by LoremFooBar** [domaindrivendev/Swashbuckle.AspNetCore#2175] opened 2021-07-30 22:23 UTC
It seems that when running the CLI, configuration from appsettings.json is not being loaded (any appsettings file, not a specific environment issue).
I created a simple repro here: https://github.com/lazyboy1/SwashbuckleCliConfigNotLoadedRepro

To reproduce:
1. Clone repo
2. Run:
    ```
    dotnet tool restore
    dotnet build
    dotnet swagger tofile --output swagger.json SwaggerCliTest/bin/Debug/netcoreapp3.1/SwaggerCliTest.dll "v1"
    ```
3. Get an error because the startup code is throwing when value of "SomeConfig" is empty, although it has a value in appsettings.json.

Using latest versions of Swashbucke.AspNetCore and Swashbucke.AspNetCore.Cli (6.1.4)

**Comment by furyd** [comment] 2021-08-06 11:57
I hit this last week as all my OpenApi and Versioning settings are configurable - the code picks up any file settings from the location it's ran in, _not_ from where the targeted assembly is.

As a temporary workaround you can copy your appsettings to the location the tool runs in, or, if you fork the code and update GetServiceProvider in the Cli project's program.cs like so:

```
private static IServiceProvider GetServiceProvider(Assembly startupAssembly)
        {
            if (startupAssembly == null)
            {
                throw new ArgumentNullException(nameof(startupAssembly));
            }

            if (TryGetCustomHost(startupAssembly, "SwaggerHostFactory", "CreateHost", out IHost host))
            {
                return host.Services;
            }

            if (TryGetCustomHost(startupAssembly, "SwaggerWebHostFactory", "CreateWebHost", out IWebHost webHost))
            {
                return webHost.Services;
            }

            var assemblyFolder = Path.GetDirectoryName(startupAssembly.Location);

            return WebHost.CreateDefaultBuilder()
               .UseStartup(startupAssembly.GetName().Name)
               .UseContentRoot(assemblyFolder)
               .Build()
               .Services;
        }
```
It'll find it.

**Comment by lazyboy1** [comment] 2021-08-08 09:47
Thanks! Running the CLI in the bin folder seems like a reasonable workaround. 
I ended up creating a separate `IHost` for the CLI to remove some dependencies that I don't need when generating the spec file, which also allowed me to avoid accessing configuration completely.

**Comment by daniloak** [comment] 2021-09-15 22:33
I had the same issue, after putting the appsettings in the folder I am running the application as @furyd mentioned it worked.

**Comment by PhilipDaniels** [comment] 2021-12-07 16:09
I just ran into this issue as well, for the same reason - various bits of config are mandatory and checked at startup time. I confirm the workaround of copying the `appsettings.json` into the run directory works.

However, it turned out to be unnecessary in my case. I was only testing running from the CLI as an intermediate step, since I was following the recipe [here](https://medium.com/@woeterman_94/how-to-generate-a-swagger-json-file-on-build-in-net-core-fa74eec3df1) to get the json file generated automatically at build time. I found that no hacks/file copies were necessary to get this to work, the snippet worked as-is:

```
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet tool restore" />
    <Exec Command="dotnet swagger tofile --output swagger.json $(OutputPath)\$(AssemblyName).dll v1 " />
</Target>

```

**Comment by mieliespoor** [comment] 2022-08-18 16:38
We have a similar issue with this.

When we try to build a dotnet 6 api, we are able to generate the file when doing so from the bin. 

However when needing to do this for a dotnetcore 3.1 api, we get exceptions from the startup.cs pointing to the appsettings.json not being loaded. Because we then also have dotnet 6 and dotnet core 3.1 installed, we need a global.json in the project root to point to the correct dotnet version. I will try and work on a sample project to reproduce this.

**Comment by martincostello** [comment] 2024-04-14 10:31
Duplicate of #1957

**Closed by martincostello** 2024-04-14 10:31 UTC
Labels: p2
