### ISSUE TITLE
Improved SwaggerHostFactory for .Net 6 Minimal APIs?

### ISSUE THREAD

**Issue by agilenut** [domaindrivendev/Swashbuckle.AspNetCore#2395] opened 2022-04-07 21:10 UTC
I'm experimenting with .Net 6 minimal apis and Swashbuckle.AspNetCore 6..3.0.

In order to verify that everything is setup correctly, I generate the swagger.json file on build using the dotnet tool and I have a xunit project that uses an OpenApiReference to that local swagger.json file to generate a swagger client. The unit tests then verify that I can call my api using the generated client against the in memory server. 

In my Program.cs, I need to use a ConfigurationProvider which accesses a remote file to obtain its configuration. That file is not always available at build time (i.e. CI builds).

Prior to Minimal APIs, to work around this issue, I had a SwaggerHostFactory class in my API project that did something like this:
```csharp
public static class SwaggerHostFactory
{
    public static IHost CreateHost()
    {
        return Host.CreateDefaultBuilder()
            .ConfigureWebHostDefaults(webHostBuilder => webHostBuilder.UseStartup<Startup>())
            .Build();
    }
}
```

This allowed me to have the configuration and a couple of other things that I didn't want to run on build in my Program.cs file and reuse all of the other logic from Startup during my build to generate the swagger file.

But, with Minimal APIs, we now have a convention that doesn't use a Startup class. All the startup code can be in the Program.cs. I really like this simplification. However, if I remove the Startup class, I'm not sure how to generate the swagger.json file on build while also overriding a couple of the config and service settings. 

Things I've tried:
* Keeping the Startup class, keeping the SwaggerHostFactory, and calling it from Program.cs. This works but I would really prefer to keep the startup code in Program.cs and avoid 2 files.
* Create extension methods for the common setup code and call them from both Program.cs and SwaggerHostFactory. This would also work but again ends up creating separate files.
* Creating functions in Program.cs and calling them from SwaggerHostFactory. This doesn't work because the functions are local functions.
* Trying to use WebApplicationFactory from Microsoft.AspNetCore.Mvc.Testing inside of my SwaggerHostFactory to create the host. I never got this to work.

I was wondering if we might be able to have a feature that would allow for a .Net 6 minimal api without a Startup.cs but still allow us to override some of the host setup. I'm not sure exactly how this would work but I was inspired by the WebApplicationFactory. If there was something like this that worked and was a part of the Swashbuckle library instead of the testing libraries, that might be a nice solution.

Is a feature like this even possible?

**Comment by Lonli-Lokli** [comment] 2022-04-30 22:28
You don't need SwaggerHostFactory with Minimal api at all, dotnet swagger will run app when you call it without swagger host factory

**Comment by agilenut** [comment] 2022-05-01 15:40
@Lonli-Lokli - my understanding is that swagger will always run the api in order to to generate the swagger.json file at build time, regardless of whether it is a minimal api or not. The point I'm making above is that I cannot let swagger run the api as it would normally run in production because, normally, the api needs to reach out to an external source to get its configuration. But at build time, when I'm generating the swagger.json file, that external source is not available. So, I need to override the configuration and a couple of DI services so that it behaves differently at build time than it does at runtime. This is why I need the `SwaggerHostFactory` and my understanding is that this is why this functionality exists. The issue now is that it is awkward to override functionality that is only in the Program.cs file with `SwaggerHostFactory` when using minimal apis. But I've seen that the `WebApplicationFactory` in `Microsoft.AspNetCore.Mvc.Testing` does it well. So, this seems like a pattern that could work for `SwaggerHostFactory` too.

**Comment by Lonli-Lokli** [comment] 2022-05-01 15:50
@agilenut you can pass environment name to swagger generation and include proper appsettings.json for this environment
```
<Target Name="SwaggerToFile" AfterTargets="AfterBuild">
        <Exec Condition="$(CI) != true" Command="dotnet swagger tofile --host http://example.com --output v1.json $(OutputPath)$(AssemblyName).dll v1" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" />
    </Target>
```

**Comment by wyatt-troia-msft** [comment] 2022-05-03 21:55
@Lonli-Lokli Amazing. Thank you! After upgrading my app to .NET 6, my post-build `dotnet swagger tofile` wouldn't work anymore due to unpopulated configurations. I'm not sure whether the upgrade caused this error by trying to access config values it didn't access in .NET 5 or by preventing the loading of config values that was happening successfully in .NET 5 (or by doing something else), but after adding `"EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development"`, the command succeeds. I already had an `appsettings.development.json` file.

**Comment by wyatt-troia-msft** [comment] 2022-05-04 17:43
Turns out that the generated Swagger didn't include any operations or schemas. I had to stop using the minimal hosting model, as suggested in [this issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2290#issuecomment-990009446).

**Comment by agilenut** [comment] 2022-05-04 17:47
@wyatt-troia-msft - That's exactly what I have had to do. Even if it did work, I'm not sure that it would be ideal in my case since I'd have to put if statements inside of my Program.cs to check for the asp.net environment to determine which configuration providers to load. 

My proposal to enhance SwaggerHostFactory could allow me to ditch the Startup.cs and avoid the if statements in Program.cs

**Comment by Lonli-Lokli** [comment] 2022-05-04 18:19
@wyatt-troia-msft @agilenut you can consider using this package 

https://github.com/dotnet/aspnet-api-versioning/blob/main/examples/AspNetCore/WebApi/MinimalOpenApiExample/Program.cs

**Comment by agilenut** [comment] 2022-05-04 18:23
@Lonli-Lokli I do actually use that package for API versioning. It's really a great package. Right now, I actually have an open issue in that repo that I'm trying to work on that is preventing me from adopting the current pre-release. 

However, to my knowledge, that package doesn't offer anything that would allow me to avoid the need for overriding the normal production behavior when I generate swagger.json at build time.

**Comment by Lonli-Lokli** [comment] 2022-05-04 18:39
@agilenut as I mentioned earlier in this thread, you can pass Environment as a parameter to Swagger generator

**Comment by agilenut** [comment] 2022-05-04 18:53
@Lonli-Lokli - First, I didn't say it but thank you for the suggestion. I actually didn't know this was a feature and it is definitely worth looking more into and knowing about. 

But, if I'm understanding that suggestion correctly, in my case, that will mean I have to add extra if statements inside of my Program.cs to know which environment I'm running in. I can't just put different config in an appsettings.json file because I have to actually change which configuration providers are loaded. I also need to change which logging providers are loaded as well as a few DI services. All of this is just to prevent my CI build from reaching out to non-existent infrastructure. In my case, for this solution to work, I think I will need to have programatic logic scattered throughout my Program.cs to perform different operations based on the given environment. I'd rather not run these checks in the normal production scenario. I only need to override them in the CI scenario. 

I could possibly make all that work. But I don't think it would be clean in my case. However, I can see how this could work well for other people who just need to pass in slightly different configuration but keep the majority of their setup the same. 

Right now, I have 2 options that I know of. 1 is the suggestion you have made to use the environment variable which, for me, would also mean extra if statements throughout Program.cs. The other is the startup class that @wyatt-troia-msft  mentioned. So, I have a couple of work arounds. But I think the main point of this GitHub issue in my mind is to suggest a new feature that could allow for the clean separation that SwaggerHostFactory provides without requiring I separate Startup.cs.

**Comment by Lonli-Lokli** [comment] 2022-05-04 18:59
@agilenut does it make sense to disable swagger generator at all on CI? I just don't see profit as the main purpose is to generate schema Json, which should be done during development cycle.

I've disabled it in my project, you can look into this link https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2395#issuecomment-1114269783

**Comment by agilenut** [comment] 2022-05-04 19:05
@Lonli-Lokli - It's a good question. For me, the reason I generate swagger.json during build is because I have another test project in the solution that uses the OpenApiReference to generate a client from the swagger file. I then run the server in an integration test and use the client against the in-memory api. This allows me to ensure that the swagger.json is generated correctly, can produce a usable client, and the client and the server can speak to each other successfully. It also allows me to test some of my authorization logic. All of these tests are run on the CI server as a quality gate to prevent bad builds and merges from being released. So, yes, in this case, I think I need it to keep the tests and the smooth dev / test process this allows.

**Comment by Lonli-Lokli** [comment] 2022-05-04 22:22
@agilenut That's interesting, 
You can still build env-specific minimal api program, you know, I am using kind of this snippet in my integration test, to ensure that application can start

```
public class StartupTests
{
    [Theory]
    [InlineData("Development")]
    [InlineData("Production")]
    public void StartupConfigure(string environmentName)
    {
        // Arrange
        var application = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.ConfigureServices(services =>
                    {
                        services.AddSingleton<ILoggerFactory, LoggerFactory>();
                        services.AddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();
                        services.AddSingleton<IHostEnvironment>(provider => new HostingEnvironment());
                        services.AddSingleton<DiagnosticSource>(new DiagnosticListener("test"));
                    })
                    .ConfigureAppConfiguration(cfgBuilder =>
                        cfgBuilder.AddJsonFile(Path.Combine(Directory.GetCurrentDirectory(), "appsettings.test.json")))
                    .UseEnvironment(environmentName);
            });
        // Act
        var serviceProvider = application.Services;

        // Assert
        serviceProvider.Should().NotBeNull();
        serviceProvider.GetRequiredService<IConfiguration>().Should().NotBeNull();
        serviceProvider.GetRequiredService<IAntiforgery>().Should().NotBeNull();
        serviceProvider.GetRequiredService<ISwaggerProvider>() .Should() .NotBeNull();        
    }
}
```

But honestly speaking I think pure extensions with if /else will be much more readable
```
public static class SmsServiceExtensions
{
  public static IServiceCollection AddSmsService(this IServiceCollection services, IHostingEnvironment env, IConfigurationRoot config)
  {
    services.Configure<SmsSettings>(config.GetSection("SmsSettings"));
    services.AddSingleton<ISmsTemplateFactory, SmsTemplateFactory>();
    if(env.IsDevelopment())
    {
      services.AddTransient<ISmsService, DummySmsService>();
    }
    else
    {
      services.AddTransient<ISmsService, SmsService>();
    }
    return services;
  }
}
```

**Comment by agilenut** [comment] 2022-06-13 16:11
@Lonli-Lokli - Thanks for the suggestion. We tried a POC of something like this to see how we'd like it. 

Unfortunately, the team did not like it. It felt like it was pushing a bunch of swagger specific branching logic further into the core api code. 

Honestly, the team didn't even like how invasive swashbuckle was before this POC. We have quit a bit of code that eventually gets shipped with the api to deal with swagger output. The team would prefer a solution that worked more as a build only tool to generate the swagger and not require any extra bits get shipped in the actual api code. Of course, this would make it much more difficult to do all the things we are doing with filters. 

But adding the logic inside of Program.cs and extension methods and making a separate environment to pass into the command in the csproj just seemed even more invasive.

**Comment by martincostello** [comment] 2024-04-14 10:30
Duplicate of #2290

**Closed by martincostello** 2024-04-14 10:30 UTC
