### ISSUE TITLE
500 on swagger json endpoint while logging response using middleware

### ISSUE THREAD

**Issue by VigneshPrasadV** [domaindrivendev/Swashbuckle.AspNetCore#288] opened 2017-01-30 13:08 UTC
When I tried logging the response with the method provided [here](http://www.sulhome.com/blog/10/log-asp-net-core-request-and-response-using-middleware), I am getting 500 on the swagger endpoint. While I am able to get the response on calling the URI. Same issue mentioned in the comment.

**Comment by domaindrivendev** [comment] 2017-02-19 04:59
Can you provide more details around the 500 response? For example, the exception that's driving it. You may need to enable the developer exception page to see this - i.e. _UseDeveloperExceptionPage_.

**Comment by VigneshPrasadV** [comment] 2017-02-21 08:33
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HL2Q5QC2C2OS": An unhandled exception was thrown by the application.

System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at PayloadLogging.PayloadLogging.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by jasneetbhatti** [comment] 2017-03-30 14:40
@domaindrivendev The issue is with [this](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/5fc96e28573d1ca40a287d7429191ff97c11b1dd/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs#L75) line.

Disposing the StreamWriter causes the underlying stream to get closed as well. Perhaps might be a good idea to just [flush it](http://stackoverflow.com/questions/2666888/is-there-any-way-to-close-a-streamwriter-without-closing-its-basestream) instead.

**Comment by rboada04** [comment] 2017-04-07 21:31
You can add the swagger middleware before adding the request/response logging middleware, so swagger requests won't get handled by the logging middleware.

`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app
               .UseSwagger()
               .UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API")
               // add logging middleware
               .UseMiddleware<LogResponseMiddleware>()
               .UseMiddleware<LogRequestMiddleware>()
               .app.UseMvc();
        }`

**Comment by Domanser** [comment] 2017-07-04 08:56
Maybe is it better not to close stream in [RespondWithSwaggerJson() method](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/5fc96e28573d1ca40a287d7429191ff97c11b1dd/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs#L75)?

For example, Swashbuckle.AspNetCore conflicts with ZNetCS.AspNetCore.Compression because stream is closed (see [this issue](https://github.com/msmolka/ZNetCS.AspNetCore.Compression/issues/1). There are some workarounds in this case: we can ignore compression for swagger.json or change order of middlewares. But in general, stream closing could be a problem.

**Comment by treziac** [comment] 2017-08-28 08:23
I hit the same issue, and ended with same analysis : it's not necessarly a good thing to close the stream (it doesn't add anything and can cause problems). Would you accept a PR to modify this?

**Comment by Grynet** [comment] 2017-11-03 11:04
Having the same problem. Seems like other issues are being opened for the same underlying problem. 
Like: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/520.

+1 on leaving the stream open. The .Net core 2 WebApi docs are lacking but I don't think ur supposed to close the stream.

**Comment by domaindrivendev** [comment] 2017-11-03 17:10
@treziac - sorry about the slow response. This does seem like a critical issue that could be easily remedied. A PR would certainly be welcomed!

**Comment by treziac** [comment] 2017-11-05 17:01
@domaindrivendev #509 solves the issue, would be nice to see it merged ;)

**Closed** 2017-11-05 18:57 UTC
Labels: waiting for response

**Comment by helloserve** [comment] 2017-11-15 11:31
Yay! Just in time with this merge. Thanks all!
