### ISSUE TITLE
Swagger file generated in cli missing paths, components (Swashbuckle.AspNetCore.Cli 5.1.0)

### ISSUE THREAD

**Issue by kepalas** [domaindrivendev/Swashbuckle.AspNetCore#1580] opened 2020-03-19 22:44 UTC
During the build process we are trying to generate the `swagger.json` file.
We are using the following command:
```
dotnet swagger tofile .\bin\Debug\netcoreapp3.1\myWebService.dll v1
```

The output that gets generated:
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "myWebService",
    "description": "myWebService",
    "contact": {
      "name": "John Doe",
      "email": "john.doe@example.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    },
    "version": "1.0"
  },
  "paths": { },
  "components": { }
}
```
As you can see, the `paths` and `components` are empty. There are no errors or warnings shown from the CLI tool.

However, if we take the `swagger.json` from the service (http://localhost:57016/swagger/v1/swagger.json), it includes all the relevant `paths` and `components`.
![image](https://user-images.githubusercontent.com/7815871/77121159-4028f300-6a43-11ea-92fb-0ae733dabdc6.png)

Can you please clarify how can we achieve the same output in CLI as from the web service?

**Comment by domaindrivendev** [comment] 2020-03-20 21:46
I've no idea why this might happen - could you create a minimal project that repro's the issue and post to github. Without a simple repro, it's hard for me to troubleshoot.

**Comment by kepalas** [comment] 2020-03-22 17:24
I created an example project and uploaded it here: https://github.com/kepalas/Swashbuckle.Repro

**Comment by kepalas** [comment] 2020-04-02 07:17
Same issue with `Swashbuckle.AspNetCore.Cli 5.2.1`. 
@domaindrivendev, any ideas why this is happening?

**Comment by domaindrivendev** [comment] 2020-04-03 10:34
I've taken a quick look and I don't think the root cause lies in the Swashbuckle library. I believe it's related to the custom `ApiExplorer` that your injecting for OData (see https://github.com/kepalas/Swashbuckle.Repro/blob/master/WebApplication1/Startup.cs#L50). Swashbuckle relies heavily on the implementation of `ApiExplorer` registered with your application. This component surfaces an `ApiDescription` for every API action method, and then SB in turn uses this to generate a corresponding Swagger/OpenAPI `Operation`. When I stepped through your sample app, I could see that the `ODataApiExplorer` is NOT surfacing the required descriptions.

So, it might be worth digging deeper into this component. @commonsensesoftware any ideas on what might be going on here?

**Comment by manisha201301** [comment] 2020-07-09 21:28
I am having the same issue. Any work-arounds for this?

**Comment by domaindrivendev** [comment] 2021-01-13 13:37
@kepalas @manisha201301 @commonsensesoftware revisiting this issue ...

I just cracked open the repro project again, and even used the following approach (https://github.com/domaindrivendev/Swashbuckle.AspNetCore#use-the-cli-tool-with-a-custom-host-configuration) to ensure the CLI tool runs in an identical host setup to the application itself, but still the same issue.

Have to say, I'm completely stumped at this point!!! So, any assistance to dig deeper and try figure it out would be greatly appreciated.

**Comment by domaindrivendev** [comment] 2021-01-14 12:38
@commonsensesoftware a combination of your insights above and another unrelated-but-actually-related issue (see #1957) are leading me to the root cause ...

With it's current implementation, the CLI tool builds an `IHost` or `IWebHost` and corresponding service container, and then uses that to retrieve an instance of `ISwaggerProvider`, but falls short of actually spinning up the application behind the scenes, and as a result (and something I'm only learning now) does not invoke the startup `Configure` method. I need to dig deeper to find an alternative approach that works - I'd prefer not have to actually spin up the app behind the scenes but it's starting to look like that may be neccessary in some shape or form.

**Comment by commonsensesoftware** [comment] 2021-01-14 17:36
@domaindrivendev excellent! My recommendation as a starting point would be to checkout the [Test Host](https://github.com/dotnet/aspnetcore/tree/master/src/Hosting/TestHost/src). You can probably use it in its entirety, but if not, it should provide a lot of good pointers on _hosting_ without hosting. The **TestServer** doesn't actually host any endpoints.

**Comment by RealGecko** [comment] 2022-10-26 15:27
Hello,

I'm not sure if it will help, but let's give it a try.

I had a similar problem, but with custom `SwaggerHostFactory.CreateHost`. The `dotnet swagger tofile (...)` returned incomplete swagger definition:
```json
{                                                                                     
  "openapi": "3.0.1",                                                                 
  "info": {                                                                           
    "title": "(...)",                                         
    "version": "v1"                                                                   
  },                                                                                  
  "paths": { },                                                                       
  "components": {                                                                     
    "securitySchemes": {                                                              
      "Bearer": {                                                                     
        "type": "http",                                                               
        "description": "Bearer token for the API to authenticate incoming requests.", 
        "scheme": "bearer"                                                            
      }                                                                               
    }                                                                                 
  },                                                                                  
  "security": [                                                                       
    {                                                                                 
      "Bearer": [ ]                                                                   
    }                                                                                 
  ]                                                                                   
}
 ```

Everything worked just fine:
- when I've accessed swagger-ui page
- when I've manually called `SwaggerHostFactory.CreateHost` during application startup:
```csharp
(...)
var host = SwaggerHostFactory.CreateHost();
var swaggerProvider = host.Services.GetRequiredService<ISwaggerProvider>();
(...)
```

To resolve this issue I had to set a value for application name, so finally my `SwaggerHostFactory.CreateHost` looks like that:

```csharp
/// <summary>
/// Custom <see cref="IHost"/> factory used for API client generation.
/// </summary>
public class SwaggerHostFactory
{
    public static IHost CreateHost()
    {
        var builder = WebApplication.CreateBuilder(new WebApplicationOptions
        {
            ApplicationName = typeof(SwaggerHostFactory).Namespace // without it, actions won't be added to swagger file
        });

        builder.Services.AddControllers();
        builder.Services.AddEndpointsApiExplorer();
        
        builder.Services.AddSynergySwaggerGen(options =>
        {
            options.SwaggerDoc("v1", new() { Title = "...", Version = "v1" });
            (...)
        });
            
        var app = builder.Build();
        app.UseSwagger();
        app.UseSwaggerUI(c =>
        {
            c.SwaggerEndpoint(...);
            (...)
        });
        app.MapControllers();

        return app;
    }
}
```

Cheers,

**Comment by Jeanot-Zubler** [comment] 2022-11-22 08:41
> To resolve this issue I had to set a value for application name, so finally my `SwaggerHostFactory.CreateHost` looks like that:

This also seems to solve my problem. As far as I see, you need to set the `ApplicationName` to your `AssemblyName`. By default this equals the project name and (on windows) is not case sensitive.

**Comment by mroberts91** [comment] 2023-01-02 16:31
I ran across this when using `Swashbuckle.AspNetCore.Cli v6.4.0`, in a `net7.0` API project.
When using `var builder = WebApplication.CreateBuilder();`, this results in the following empty Open API document.
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "V1"
  },
  "paths": { },
  "components": { }
}
```

But to resolve this, simply pass `args` to the `CreateBuilder` method. I found that this results in a fully built Open API file.

`var builder = WebApplication.CreateBuilder(args);`

**Comment by Ducki** [comment] 2023-03-08 11:33
This is still a problem in 6.5.0

**Comment by dosper7** [comment] 2023-03-29 15:03
Same here, I'm using .net 7 with minimal API's.

**Comment by 1bberto** [comment] 2024-01-11 15:39
facing the same issue with `.net8`

**Comment by martincostello** [comment] 2024-04-14 10:27
Duplicate of #1957

**Closed by martincostello** 2024-04-14 10:27 UTC
Labels: p2
