### ISSUE TITLE
[BUG]summary param explain does't work at [HttpPost] and [FromForm]

### ISSUE THREAD

**Issue by xkylw** [domaindrivendev/Swashbuckle.AspNetCore#2221] opened 2021-09-10 09:27 UTC
summary param explain does't work at [HttpPost] and [FromForm]
![QQ截图20210910172643](https://user-images.githubusercontent.com/12201929/132832482-1a99435d-9a11-49b1-a867-a2e13973194f.jpg)

**Comment by xkylw** [comment] 2021-09-13 06:22
![QQ截图20210903093025](https://user-images.githubusercontent.com/12201929/133033623-fecde4b8-2b54-4388-9bfe-6cecdc1950cb.jpg)

**Comment by xkylw** [comment] 2021-09-13 06:22
![QQ截图20210913142116](https://user-images.githubusercontent.com/12201929/133033693-3fcc7cd0-5eb7-4f48-a13f-a8da66d581d1.jpg)

**Comment by xkylw** [comment] 2021-09-13 06:27
anybody encounter this problem?

**Comment by PaulKlein** [comment] 2021-09-16 21:58
I'm running into this same problem

**Comment by jacobjmarks** [comment] 2021-11-12 00:23
Duplicate of #2062

**Comment by alexminza** [comment] 2023-10-06 11:37
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2519

**Comment by martincostello** [comment] 2024-05-04 15:04
Duplicate of #2062

**Closed by martincostello** 2024-05-04 15:04 UTC
