### ISSUE TITLE
Mapped Routes not showing up with net6.0 Minimal APIs

### ISSUE THREAD

**Issue by dansiegel** [domaindrivendev/Swashbuckle.AspNetCore#2440] opened 2022-06-13 15:12 UTC
# Description

When using net6.0 Minimal APIs, routes mapped which only access the HttpContext return the `IEndpointRouteBuilder` instead of the `RouteHandlerBuilder`, these mapped routes will not appear in the generated Swagger definition. When using Minimal APIs I can map multiple API's like:

```cs
app.MapGet("/hello-world", () => "Hello World");
app.MapGet("/hello-dan", () => "Hello Dan");
app.MapGet("/hello-{name}", (name, context) =>
{
    context.Response.StatusCode = 200;
    return context.Response.WriteAsync($"hello {name}");
});
```

Each of these will show up in the generated API Docs. However if I require access to the HttpContext but do not require have any parameters I need to specify (as shown below), no swagger docs will be generated for this endpoint:

```cs
app.MapGet("/hello-world", context => context.WriteAsync("Hello World"));
```

## Known Workaround

If this updated as follows, it will show up in the generated API Docs:

```cs
app.MapGet("/hello-world", (context, cancellationToken) => context.WriteAsync("Hello World", cancellationToken));
```

**Comment by martincostello** [comment] 2024-04-14 10:24
Duplicate of #2290

**Closed by martincostello** 2024-04-14 10:24 UTC
