### ISSUE TITLE
Different enum string camel casing strategy than ASP.NET Core

### ISSUE THREAD

**Issue by ackginger** [domaindrivendev/Swashbuckle.AspNetCore#1162] opened 2019-05-24 16:19 UTC
We are seeing a difference in behaviour for your implementation of ToCamelCase compared to that used by the built in Json serializer in .Net Core 2.2:

https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json/Utilities/StringUtils.cs#L149

Specifically for example:
Enum member = FOOBar
Json.NET = fooBar
Swashbuckle = fOOBar

Whilst I accept the enum member isn't exactly following C# naming conventions, it seems inconsistent to be generating a swagger doc using a different format to that which the serializer will use at runtime. 

This is causing us issues as our generated TypeScript client is out of sync with the returned values.

**Comment by ackginger** [comment] 2019-05-29 09:32
Additionally, while I don't have a quick way to test this as I'm still running v4, it looks like you have regressed the EnumMember attribute fixes from #619 in the v5 beta.

**Comment by MikeBeaton** [comment] 2019-05-31 10:17
@ackginger Worth mentioning that support for default values (available on API method parameters and compound object properties) for enums, when enums are being output as strings, would require some non-trivial refactoring to work with `EnumMember` renaming of enum members (AFAICT #1165).

The problem is that the `OpenApiSchema` for an enum does not contain enough info to map an enum string name from the C# to JSON, in general (it just contains enough, if only case changes have been made); i.e. at the point in the code when default values for enums are calculated, currently, there is not enough info to map the default value from C# to JSON.

**Comment by ti82** [comment] 2019-06-13 20:49
Furthermore, if the property is a complex object type, nested properties are not camel cased, because ToCamelCase only looks at the first character in the ApiParameterDescription.Name. This should be doing a split on the '.' separator and then calling ToLowerInvariant on all parts, not just the first.

**Comment by domaindrivendev** [comment] 2019-08-09 12:49
For now, I've (re)added support for `EnumMember` which doesn't solve this issue but DOES provide a workaround. See 6f07192e3d84f9c9b9259df3d9f260cd09fe7a3c.

On the back of [AspNetCore decoupling from Json.NET](https://github.com/dotnet/announcements/issues/90), I plan to do the same with Swashbuckle and so at this point I'm not sure about "coupling" further to that library.

I agree we still have a legitimate issue here but I'm not sure exactly how I'd like to proceed and don't have the headspace available right now to think it through. So, with a workaround now in place(i.e. explicit names via `EnumMember`), I think this issue has a far lower priority than just getting the 5.0.0 milestone finished and released. Moving to backlog.

**Comment by domaindrivendev** [comment] 2019-09-13 09:53
Should be fixed by bcf4254313c03c08692875920bb66a6f211d337f. Official Nuget release is in the works but you can try out this change by downloading the latest preview package from myget.org.

**Closed by domaindrivendev** 2019-09-13 09:53 UTC
