### ISSUE TITLE
Add ability to upload single and multiple files.

### ISSUE THREAD

**Issue by grishchenkoa** [domaindrivendev/Swashbuckle.AspNetCore#911] opened 2018-10-12 21:06 UTC
Looks like swagger has ability to upload [one and multiple files](https://swagger.io/docs/specification/2-0/file-upload/), but package can't to do that. Can you please files upload support.
Single file upload can be implemented based on custom `IOperationFilter` for `IFormFile`. But what to do with `IFormFileCollection` or `IEnumerable<IFormFile>`?

**Comment by yawnston** [comment] 2018-10-19 07:06
This looks like a duplicate of #193. Take a look at @domaindrivendev's reply from that issue:

> Support for parameters and properties of type `IFormFile` now merged into master. Will be generally available with the upcoming 4.0.0 release. NOTE: `IFormFileCollection` and `IEnumerable<IFormFile>` is still not supported as Swagger 2.0 doesn't support an array of file parameters (see [swagger-api/swagger-ui#823](https://github.com/swagger-api/swagger-ui/issues/823) for more details).
> 
> You can try it now with the latest preview package on myget.org:
> https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

**Closed** 2018-10-19 07:19 UTC

**Comment by badJaguar** [comment] 2019-07-25 21:10
If I describe IFormFile inside the Type = "array"  as it described in expected body (field by field), will it work as array of IFormFile or not? Maybe someone experimented.
