### ISSUE TITLE
Can't use Swashbuckle.AspNetCore.Cli with SwaggerHostFactory to generate swagger.json correctly in Asp.net 6 without Startup class

### ISSUE THREAD

**Issue by SamGuoMsft** [domaindrivendev/Swashbuckle.AspNetCore#2579] opened 2022-12-22 23:48 UTC
@domaindrivendev, 

I am trying to use Swashbuckle.AspNetCore.Cli and SwaggerHostFactory to generate swagger.json.

The generated swagger.json always empty for path and compoments, which is strange.
I used the new host model without startup to create host.
public class SwaggerHostFactory
```
{
    public static IHost CreateHost()
    {
        var builder = WebApplication.CreateBuilder();
        builder.Services.AddControllers();
        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddSwaggerGen();

        var app = builder.Build();
        if (app.Environment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI();
        }
        app.UseHttpsRedirection();
        app.UseAuthorization();
        app.MapControllers();
        return app;
    }
}
```
As you can see the path is empty.
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "dotnet-swagger",
    "version": "1.0"
  },
  "paths": { },
  "components": { }
}
```
But if I used the old style with Startup from SwaggerHostFactory and it worked fine. Feels like it is a bug.

**Comment by Havunen** [comment] 2024-02-24 07:54
Can you test if DotSwashbuckle solves this issue?

**Comment by martincostello** [comment] 2024-04-14 10:53
Duplicate of #2290

**Closed by martincostello** 2024-04-14 10:53 UTC
