### ISSUE TITLE
Operation Parameter Object does not respect the Required Attribute

### ISSUE THREAD

**Issue by devlynx** [domaindrivendev/Swashbuckle.AspNetCore#152] opened 2016-08-14 15:56 UTC
When a RequiredAttribute is applied to an operation parameter the resulting Swagger.json file shows "required": false instead of "required": true. This problem can easily be seen with the Basic test program observing the results of the CrudActionsController Create method where the product parameter is attributed with the Required attribute.

```
public class CrudActionsController
{
    [HttpPost]
    public int Create([FromBody, Required]Product product)
    {
        return 1;
    }
}
```

Looking at the SwaggerGenerator class, CreateParameter method, the only apparent situation where required is set to true is when the source is "path" (a requirement of the OpenAPI Specification for the "path" source). 

Please add support for sources other than "path" to have required parameters.

Thanks!

**Comment by rynowak** [comment] 2016-08-15 15:10
MVC doesn't currently support validation attributes directly on parameters. /cc @domaindrivendev is this a feature Ahoy adds?

**Comment by cherici-simone** [comment] 2017-01-20 11:36
Any news on it? I have the same problem with [FromBody] parameters that are marked as "optional" in generated doc.

**Comment by domaindrivendev** [comment] 2017-01-25 06:50
Correct me if I'm wrong @rynowak but using the _RequiredAttribute_ on an action parameter doesn't really make sense. The parameter value will never be null as the framework will instantiate it even if no payload was provided with the request.

So, taking a step back - I'm wondering how people are implementing required parameter behavior in their Core API's - regardless of Swashbuckle. It would be ideal for Swashbuckle to hook into that instead of a meaningless attribute so that the documentation remains fully in-sync with actual behavior.

**Comment by domaindrivendev** [comment] 2017-01-25 06:51
@devlynx - given that _RequiredAttribute_ in your example doesn't actually have any effect on your runtime behavior, how are you validating that the parameter is provided?

**Comment by rynowak** [comment] 2017-01-25 07:20
Yep. There's no sensible reason to put `[Required]` on a parameter right now. It's something we might consider adding in the future.

**Comment by dario-hd** [comment] 2017-02-08 12:33
@domaindrivendev is _does_ make sense. Here's a screenshot after a request using Postman.

![untitled](https://cloud.githubusercontent.com/assets/14803089/22737336/f5f5cae8-ee02-11e6-9f47-96c096fdd271.png)

As you can see the request body could be null.

**Comment by dario-hd** [comment] 2017-02-08 14:22
By the way, here's how I did it:

    using System.Collections.Generic;
    using System.Linq;

    using Swashbuckle.AspNetCore.Swagger;
    using Swashbuckle.AspNetCore.SwaggerGen;

    public class SetBodyParameters : IOperationFilter
    {
        public void Apply(Operation operation, OperationFilterContext context)
        {
            if (operation.Parameters == null || !operation.Parameters.Any())
            {
                return;
            }

            SetBodyParametersAsRequired(operation);
        }

        private void SetBodyParametersAsRequired(Operation operation)
        {
            IEnumerable<IParameter> bodyParameters = operation.Parameters.Where(p => p.In == "body");

            foreach (IParameter bodyParameter in bodyParameters)
            {
                bodyParameter.Required = true;
            }
        }
    }

And in the `Startup.cs`:

    services.AddSwaggerGen(c =>
    {
        // ...
        c.OperationFilter<SetBodyParameters>();
        // ...
    });

**Closed** 2017-02-11 05:48 UTC
Labels: waiting for response

**Comment by Dresel** [comment] 2017-02-20 14:40
In combination with something like a `BodyRequiredConvention` [here](https://github.com/aspnet/Mvc/issues/4750#issuecomment-232693356) it makes sense as OperationFilter.

	public class MarkBodyParameterAsRequiredOperationFilter : IOperationFilter
	{
		public void Apply(Operation operation, OperationFilterContext context)
		{
			BodyParameter bodyParameter = operation.Parameters?.OfType<BodyParameter>().SingleOrDefault();

			if (bodyParameter != null)
			{
				bodyParameter.Required = true;
			}
		}
	}

**Comment by nosider** [comment] 2017-03-09 08:43
Could someone please confirm whether it is by design, and is expected, for each Project to implement its own equivalent of a 'required' attribute for Controller Action parameters?

The Action parameters which fails to be bound (during the model-binding stage, for example sending an empty json POST) will not have their respective validations called (since ValidationVisitor does not seem to call validations on a null model). This seems to leave a choice between:
1) Checking every required parameter for null in every Action
2) Implementing a custom convention-based OperationFilter
3) Customising the model-binding process to perform the check. _(very heavy-handed approach I believe)_

Is there another approach we can take?

I looked at customising IObjectModelValidator, but it does not work either, because it has no idea which parameter is being validated (or whether it is even a parameter at all)

Thank You for any clarification

**Comment by Morcatko** [comment] 2017-05-16 10:25
@domaindrivendev
> Yep. There's no sensible reason to put [Required] on a parameter right now. It's something we might consider adding in the future.

I agree there is no reason to have [Required] because of a runtime, but consider this scenario. 
* Lets take an endpoint to search a data as an example. the `string searchPhrase` is mandatory parameter for an endpoint to run.
* We use Swashbuckle.AspNetCore to generate swagger.json.
* This file is later used by [swagger-codegen](https://github.com/swagger-api/swagger-codegen) to get typescript files that are used by frontend
* Unfortunatelly the generated typescript classes have all properties as optional
`{  "searchPhrase"?: string; }`

It is not a big deal. Just an idea where this feature might make a sense
