### ISSUE TITLE
Swagger CLI generated spec missing Minimal API endpoints (but they do show up in Swagger UI)

### ISSUE THREAD

**Issue by Jon-Hilton** [domaindrivendev/Swashbuckle.AspNetCore#2463] opened 2022-07-20 14:32 UTC
I have a requirement to use minimal APIs in a .NET 6 application, but with generic host, rather than `WebApplicationBuilder` (for reasons of not breaking the existing build/release pipelines, at least in the short term).

In this scenario, when I add minimal API endpoints, they show up in the Swagger UI, but if I then try to generate a spec using the CLI they are missing.

Steps to recreate:
1. Create a new .NET 5 application
2. Update it to .NET 6 (by changing the .NET version number in csproj)
3. Register a minimal API endpoint in startup.cs `Configure` method:

``` csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapGet("HelloWorld", (int subscriberId) => "Hello World").WithName("Test");
    endpoints.MapControllers();
});
```

4. Add this call to `ConfigureServices`

``` csharp
services.AddEndpointsApiExplorer();
```

5. Update Swashbuckle.AspNetCore to 6.4.0

Launch the app, notice that the endpoint shows up in Swagger UI.

Launch the swagger CLI to generate a spec from the resulting web application's .dll file:
``` powershell
swagger tofile --output api-spec.json ./bin/Debug/net6.0/YourWebApplication.dll v1
```

The minimal api endpoint for "Hello World" is not included in the generated api-spec.json file (but the controller actions are).

**Comment by bibalek** [comment] 2023-02-21 12:17
I can confirm it still exists on Swashbuckle.AspNetCore 6.5.0.

**Comment by martincostello** [comment] 2024-04-22 08:15
Duplicate of #2290

**Closed by martincostello** 2024-04-22 08:15 UTC
