### ISSUE TITLE
Swagger does not obey FromHeader attribute in header as specified in .net core

### ISSUE THREAD

**Issue by V4A001** [domaindrivendev/Swashbuckle.AspNetCore#1938] opened 2020-12-21 10:52 UTC
https://github.com/swagger-api/swagger-ui/issues/6736

This does not generate the proper headers in the GUI.
public async Task<IActionResult> Order([FromHeader] MyClassHeader myclassHeader) {
See also this post related to 1 class for multiple headers:
https://stackoverflow.com/questions/57768912/how-to-use-fromheader-attribute-with-custom-model-binding-in-asp-net-core-2-2

Swagger makes this like:
myclassHeader=param1, param2 instead of param1=value1 and param2=value2 in the header

Swagger-UI version: latest
Swagger/OpenAPI version: open api 3

**Comment by domaindrivendev** [comment] 2021-01-12 23:50
Please create a minimal project (i.e. start from blank project) that repro's your issue and post it to github where I can pull it down and troubleshoot further?

**Comment by leejgdh** [comment] 2021-01-22 13:15
https://github.com/leejgdh/SwaggerExample

**Comment by V4A001** [comment] 2021-01-22 13:42
@leejgdh : thank you for adding it. The todo controller has the FromHeader which is not working.

`[HttpGet("{Id}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ResponseGetTodo))]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public IActionResult Get([FromHeader] Sign header, [FromRoute] Guid Id)`

**Comment by leejgdh** [comment] 2021-01-23 02:19
yes, how to working? to use swagger ui.
i hope to testing api use from swagger ui.

**Comment by V4A001** [comment] 2021-01-23 10:44
I have limited time to look into it. I would clone the source code and run through it to see what needs to be changed to have this working. I use postman now and just add the headers manually.

**Comment by leejgdh** [comment] 2021-01-24 07:27
if use post man add header value is working. but swagger ui header value is not working.

**Comment by domaindrivendev** [comment] 2021-02-05 14:19
This looks to be an upstream issue with `ApiExplorer` in ASP.NET Core. I create the following ticket, and we can continue to track here:

https://github.com/dotnet/aspnetcore/issues/29931

**Comment by nZeus** [comment] 2022-03-08 13:45
I faced the same issue.
This does not seem to be a bug in ASP.NET Core, but the generated OpenAPI json file seems to be incorrect.
Mapping in ASP.NET Core is working fine.
The work-around is to add `[FromQuery]` attribute to the action parameter

**Comment by domaindrivendev** [comment] 2022-03-08 19:13
Yes the error ultimately manifests in the generated Open API file but the root cause is in the ApiExplorer component from ASP.Net Core, as per the referenced upstream issue

**Comment by NicolasChettyMri** [comment] 2022-05-04 08:52
Was there a solution that involves keeping the [FromHeader]?

**Comment by blalonde** [comment] 2022-05-17 14:13
This seems to be a casting issue, if you specify your parameter as a string, I receive it correctly.

**Comment by aldinei-sampaio** [comment] 2022-08-04 20:06
When you name the argument "authentication", the Swagger UI correctly shows it but never sends the header.

```
        [HttpGet]
        public ActionResult Get([FromHeader] string authentication)
```

If you name the argument for something like "test", it works ok.

Obs.: I don't want to use basic authentication or anything like that. Just need to receive a header with that name.

**Comment by ZippoLag** [comment] 2022-08-23 22:07
Gah, struggled for a while until I found this issue! Thank you for the [FromQuery] workaround, I hope it doesn't backfire in some way I'm not aware.

**Comment by dsum27** [comment] 2023-08-09 13:24
For those who are reviewing, this approach is effective.

```C#
[ApiController]
[Route("api/[controller]")]
public class SampleController : ControllerBase
{
    [HttpGet("get-header-info")]
    public IActionResult GetHeaderInfo(
        [FromHeader(Name = "x-header-name")] string xHeaderName, 
        [FromHeader(Name = "User-Agent")] string userAgent)
    {
        var headers = new HeaderInfo
        {
            XHeaderName = xHeaderName,
            UserAgent = userAgent
        };

        if (string.IsNullOrEmpty(headers.XHeaderName))
        {
            return BadRequest("x-header-name is not provided.");
        }

        return Ok($"Received x-header-name: {headers.XHeaderName}, User Agent: {headers.UserAgent}");
    }
}
```

**Comment by martincostello** [comment] 2024-05-04 15:51
Closing as external.

**Closed by martincostello** 2024-05-04 15:51 UTC
Labels: upstream-aspnetcore
