### ISSUE TITLE
.net core 2.0 preview 3 problems

### ISSUE THREAD

**Issue by DukeCheng** [domaindrivendev/Swashbuckle.AspNetCore#444] opened 2017-07-11 13:16 UTC
when I access to /swagger path, it return following error:

MissingMethodException: **Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'**.
Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

> Is there have a new beta version for .net core 2.0 preview/nightly rtm version release for swagger?

**Comment by tillig** [comment] 2017-07-11 13:45
Duplicate of #438.

**Closed** 2017-09-12 06:23 UTC

**Comment by Codelet** [comment] 2017-11-22 13:08
It's not.
This one complains about not finding a constructor with string parameter because netstandard2.0 version of EntityTagHeaderValue constructor uses StringSegment parameter instead.

**Comment by MelbourneDeveloper** [comment] 2018-01-10 03:00
I'm still getting this.
