### ISSUE TITLE
Cli Swagger.json can't resolve anything

### ISSUE THREAD

**Issue by josh-hemphill** [domaindrivendev/Swashbuckle.AspNetCore#2622] opened 2023-03-17 20:09 UTC
Potential continuation of #1580 and a couple others I can't find now; however, none of the solutions seemed to work.
I'm just trying to start a fresh C# .NET7 web api + static website (with forwarding set for Vite during development, though that shouldn't affect anything here)

I tried recreating the `Startup.cs` file/class and usage as described by others, but that didn't seem to affect it. So for brevity, I've gone back to a single `Program.cs` file I share below.
I've tried swapping the `ApiExplorer` in various ways and removing the options I set, all to no avail.

I'm at my wits end with this, which is why I'm posting here.
If this gets figured out, I'd be happy to submit a PR for a getting started example for NET7+ so no one else has to go through this.

Here's the whole program initialization:
```cs
using Microsoft.Extensions.Options;
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;
using Microsoft.AspNetCore.Mvc.Versioning;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(new WebApplicationOptions
{
	ApplicationName = "TheNamespaceIUseForEverything",
	Args = args
});
// Add services to the container.

var config = builder.Configuration;
var parsedRequiredConfig = new ParsedRequiredConfig(config);
var services = builder.Services;
var env = builder.Environment;


services.AddControllers().AddJsonOptions(options =>
	{
		options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
		options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
	});
services.AddMvc();
services.AddEndpointsApiExplorer();
services.AddApiVersioning(options =>
	{
		options.AssumeDefaultVersionWhenUnspecified = true;
		options.ApiVersionReader = new UrlSegmentApiVersionReader();
		options.UseApiBehavior = false;
	});
services.AddVersionedApiExplorer(options =>
	{
		options.GroupNameFormat = "VVV";
		options.SubstituteApiVersionInUrl = true;
	});

services.AddSwaggerGen();

// services.Configure<SwaggerGenOptions>(Configuration.GetSection("SwaggerGen"));

services.Configure<SwaggerOptions>(config.GetSection("Swagger"));
services.AddTransient<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>();

var app = builder.Build();


if (env.IsDevelopment())
{
	app.UseDeveloperExceptionPage();
}
else
{
	// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
	app.UseHsts();
}

app.UseStaticFiles()
	.UseApiVersioning()
	.UseRouting()
	.UseEndpoints(endpoints =>
	{
		endpoints.MapControllers();
	})
	.UseSwagger();

app.MapControllerRoute(
	 name: "default",
	 pattern: "{controller}/{action=Index}/{id?}");

app.MapFallbackToFile("index.html");

app.Run();
```
The SwaggerGenOptions:
```cs
public class ConfigureSwaggerOptions : IConfigureOptions<SwaggerGenOptions>
{
	readonly IApiVersionDescriptionProvider provider;

	public ConfigureSwaggerOptions(IApiVersionDescriptionProvider provider) =>
		 this.provider = provider;

	public void Configure(SwaggerGenOptions options)
	{
		foreach (var description in provider.ApiVersionDescriptions)
		{
			options.SwaggerDoc(
				$"OpenAPI_v{description.GroupName}",
				new OpenApiInfo()
				{
					Title = $"Doc for API v{description.ApiVersion}",
					Description = "",
					Version = $"v{description.ApiVersion.ToString()}",
				});
		}
		var xmlCommentsPath = Path.Combine(
			System.AppContext.BaseDirectory,
			"ApiComments.xml"
		);
		options.IncludeXmlComments(xmlCommentsPath, true);
	}
}
```
The Swagger section of the settings just sets:
```json
"Swagger": {
    "RouteTemplate": "docs/{documentName}/openapi.json"
  }
```

**Comment by Havunen** [comment] 2024-02-18 20:18
Have you tested with DotSwashbuckle and .Net8 thst has most likely this issue resolved

**Comment by martincostello** [comment] 2024-04-14 10:24
Duplicate of #2290

**Closed by martincostello** 2024-04-14 10:24 UTC
