### ISSUE TITLE
"library.dll does not contain an entry point" error when using "TargetFrameworks" vs "TargetFramework"

### ISSUE THREAD

**Issue by andrewmcclellankibo** [domaindrivendev/Swashbuckle.AspNetCore#1511] opened 2020-01-30 19:29 UTC
Creating a dll using .net core 3.1
Reference: Swashbuckle.AspNetCore Version=5.0.0

Build -> compiles succesfully

Change: `<TargetFramework>netcoreapp3.1</TargetFramework>`
To:  `<TargetFrameworks>netcoreapp3.1;</TargetFrameworks>`
Or What i'm using: `<TargetFrameworks>netcoreapp3.1;netstandard2.0;net461;</TargetFrameworks>`

Compile -> failure, two errors:
"library.dll does not contain an entry point"
"The command "dotnet "blah\microsoft.extensions.apidescription.server\3.0.0\build\/../tools/dotnet-getdocument.dll" --assembly "library.dll" --file-list "obj\library.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.1" --output "obj" --project "library" --assets-file "library\obj\project.assets.json" --platform "AnyCPU" " exited with code 3."

I found that that comand does not run when using just TargetFramework.

There is a workaround: underneath <TargetFrameworks> add <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>

But this doesn't seem like the expected requirement

**Comment by gloriali2011** [comment] 2020-04-13 19:27
Hi there, I have the same issue, did you find out the root cause and ways to fix the error? Thank you!

**Comment by gloriali2011** [comment] 2020-04-13 20:20
Hi there, I have the same issue, did you find out the root cause and ways to fix the error? Thank you!

**Comment by SonicGD** [comment] 2020-09-22 12:16
I have same problem when cross-target library to 3.1 and 5.0

```xml
<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
```

Adding 
```xml
<OpenApiGenerateDocumentsOnBuild>false</OpenApiGenerateDocumentsOnBuild>
```
helps.

**Comment by domaindrivendev** [comment] 2021-01-18 21:45
@andrewmcclellankibo are you still experiencing this problem with the latest version of SB (`5.6.3` at time of writing)? If so, please create a minimal app (i.e. starting from empty project) that repro's the issue and post to github so I can pull it down and troubleshoot. Thx

**Comment by liuyongtao** [comment] 2021-01-22 04:42
I have the same problem

**Comment by aliabusaleh** [comment] 2021-01-25 13:54
chick this #1967 it might help

**Comment by domaindrivendev** [comment] 2021-02-05 13:24
SB doesn't currently support apps that target `net461` but not sure if that's the OP's issue. If this is happening for other targets then I need someone to create a minimal app that repro's it and post to github where I can pull down and troubleshoot. I'm going to close the issue until someone provides that.

**Closed by domaindrivendev** 2021-02-05 13:24 UTC
Labels: responded

**Comment by jonathh21** [comment] 2021-09-06 20:02
I've got this - targeting core 3.1 and .net 5

**Comment by ravimittal84** [comment] 2021-09-07 11:37
Add this to your csproj 
```
<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
```

**Comment by wsaeed** [comment] 2022-04-14 05:57
> I came across the same issue when attempting to multi-target .NET 5.0 and 6.0 @domaindrivendev, I've created a minimal solution that reproduces the issue here: https://github.com/jonclare/SwashbuckleBuildErrors
> 
> Can you re-open this issue?

I'm also experiencing the same issue when multi-targeting .net 5 and .net 6.

**Comment by GitBasse** [comment] 2022-07-08 09:06
I'm also getting this error with Framework Version 4.8

**Comment by ben-page** [comment] 2023-09-11 20:05
@domaindrivendev Hi, here's an example of the problem using .NET Core 6 & 7. The build works with `TargetFramework`, but not `TargetFrameworks`. Can you reopen this issue?

https://github.com/ben-page/SwashbuckleMultiTargetError
