### ISSUE TITLE
Response sample not generating for 201

### ISSUE THREAD

**Issue by adnan-kamili** [domaindrivendev/Swashbuckle.AspNetCore#711] opened 2018-04-28 12:47 UTC
Hi,

I recently upgraded to Asp.Net Core 2.1. It allows adding type to ActionResult which nicely displays in as swagger response sample for 200. But if I add `[ProducesResponseType(201)]`, then the response sample is not generated.

```csharp
       [HttpPost]
       [ProducesResponseType(201)]
       public async Task<ActionResult<PolicyDto>> Create([FromBody] PolicyViewModel viewModel)
       { ...
```

**Comment by domaindrivendev** [comment] 2018-05-02 20:43
Try including the return type with the attribute:

```csharp
       [HttpPost]
       [ProducesResponseType(PolicyDto, 201)]
       public async Task<ActionResult<PolicyDto>> Create([FromBody] PolicyViewModel viewModel)
       { ...
```

**Comment by domaindrivendev** [comment] 2018-05-05 00:46
Not according to the semantics of the `ProducesResponseTypeAttribute`.
> A filter that specifies the type of the value and status code returned by the action

This was introduced in ASP.NET Core to be explicit about the response type that's surfaced up through ASP.NET Core's built-in metadata layer - `ApiExplorer`. It completely overrides the status _and_ response type that would be otherwise inferred from the signature. So, if you don't specify a type, `ApiExplorer` assumes your saying there's no content returned.

**Comment by NatMarchand** [comment] 2018-06-01 15:22
I'm reopening the issue as ASP.Net Core 2.1 is released.
We can see this in the doc (https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.1#actionresultt-type)

> ActionResult<T> offers the following benefits over the IActionResult type:
The [ProducesResponseType] attribute's Type property can be excluded.

And they also talk about it in this section https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml#describe-response-types where they explicitly don't put the type.

**Comment by zuckerthoben** [comment] 2018-06-04 13:55
I support this request. To fully support ASP.NET Core 2.1 Swashbuckle should react to the new behavior of [ProducesResponseType]. As stated by @NatMarchand people will start dropping the Type property for the default response type.

**Comment by domaindrivendev** [comment] 2018-06-04 17:16
Off the top of my head this points to a bug in ApiExplorer. Swashbuckle builds on top of this, inspecting ApiDescription.SupportedResponseTypes to build the corresponding Swagger Responses. If 2.1 introduced a change to the semantics of ProducesResponseType, then that should be reflected by ApiExplorer.

I’ll need to dig deeper but I suspect this is the root cause

**Comment by domaindrivendev** [comment] 2018-06-05 06:15
I confirmed this to be the case and submitted the following issue in the Mvc repo:
https://github.com/aspnet/Mvc/issues/7871

**Comment by domaindrivendev** [comment] 2019-02-25 19:19
Closing as the upstream issue is now resolved as of ASP.NET Core 2.2

**Closed by domaindrivendev** 2019-02-25 19:19 UTC
Labels: waiting for response
