### ISSUE TITLE
Support .Net Standard 2.0

### ISSUE THREAD

**Issue by daniloro** [domaindrivendev/Swashbuckle.AspNetCore#468] opened 2017-08-21 12:01 UTC
Hi, it seems interesting that Swashbuckle supports .Net Standard 2.0.

I have new apis that use the new .Net Standard 2.0 but I can not use Swashbuckle.

Regards

**Comment by daniloro** [comment] 2017-08-21 12:15
When I search by "Swashbuckle.AspNetCore" on Visual Studio 15.3.1 NuGet Package Explorer, Version combobox appears in blank.

I am using .Net Core 2 WebApi project on Visual Studio 15.3.1

![screen shot 2017-08-21 at 09 09 01](https://user-images.githubusercontent.com/2098832/29518616-6ab9c790-8650-11e7-83da-e0102b4d7026.png)

**Comment by tillig** [comment] 2017-08-21 12:32
Duplicate of #464

The 15.3.1 tooling has introduced a lot of problems in my projects. For example, Roslyn analyzers started throwing exceptions and failing to run. I'd probably blame the tooling for this, especially since Swashbuckle has no control over how VS displays things.

**Comment by daniloro** [comment] 2017-08-22 11:53
Following the .NET Standard DOC and NetStandard2 GitHub page .NET CORE 2 only support .Net Framework 4.6.1 as platform, and Swashbuckle.AspNetCore only support .Net Framework 4.5.1, this is why the VS not show an option to install Swashbuckle on .NetCore2 projects.

If the Swashbuckle would support .NetFramework 4.6.1, the Swashbuckle would be compatible with .NetCore1 and .NetCore2 projects following .NET Standard DOC's.
[https://docs.microsoft.com/en-us/dotnet/standard/net-standard](url)

This is my vision of the problem, feel free to correct me if I are wrong

![screen shot 2017-08-22 at 08 18 06](https://user-images.githubusercontent.com/2098832/29563256-1c29e448-8713-11e7-985a-144d5ef2881c.png)

![screen shot 2017-08-22 at 08 09 16](https://user-images.githubusercontent.com/2098832/29563266-26bf0de8-8713-11e7-835a-2cb2a7305fa1.png)

**Comment by tillig** [comment] 2017-08-22 15:16
Yeah, that's not really how it works.

Take `netstandard` out of the picture for a second and just think about .NET framework. If you wrote something in .NET 2.0 it should still work - without recompile - on .NET 4.0. If you wrote it on .NET 4.0, it should still work on .NET 4.5 or .NET 4.6. However, the other way isn't true - if you wrote it in .NET 4.5 it won't work against .NET 2.0.

This is how `netstandard` works, too - if you write it for compatibility with `netstandard 1.2`, for example, it will work with stuff that is built against `netstandard 2.0`... but it _won't_ work with things that target `netstandard 1.0` or `netstandard 1.1`. You can move from left to right on the chart but you can't move from right to left.

Swashbuckle.AspNetCore 1.0.0 targets `netstandard 1.6` so it is compatible with `netstandard 2.0` - left to right. If compatibility was changed to target `netstandard 2.0` it would hose all the people who have .NET Core 1.0 or 1.1 projects because that's right to left on the chart - you can't go backwards. Libraries target the earliest possible footprint.

By way of comparison, ASP.NET Core 2.0 has [updated their minimum to `netstandard 2.0`](https://github.com/aspnet/Mvc/blob/rel/2.0.0/src/Microsoft.AspNetCore.Mvc/Microsoft.AspNetCore.Mvc.csproj#L7) because they require new APIs that are only in `netstandard 2.0` and/or consume very specific breaking changes there. If they didn't need those new APIs, they wouldn't have updated. Lower `netstandard` == more compatible with more stuff.

So... it's tooling. To verify that I created a brand new web app targeting .NET Core 2.0 and successfully added Swashbuckle.AspNetCore 1.0.0 to that project:

![Adding Swashbuckle to .NET Core 2.0 project](https://user-images.githubusercontent.com/1156571/29572468-4ad65634-8711-11e7-9ca1-91387b746ee4.PNG)

If you're not seeing a version show up, it could be a lot of things, none of which are Swashbuckle.

- Bad cache: Close Visual Studio, delete your `.vs` folder and all the `bin` and `obj` folders in your solution. Open it up again and retry. Also consider clearing out your NuGet local cache to ensure things are being retrieved fresh from NuGet and not from a cached local copy.
- Network problem: Maybe your network connection got interrupted while it was trying to get version info.
- Install problem: Perhaps there's something in your Visual Studio installation that's been corrupted and is erring out under the covers.
- Tooling version collisions: Can't tell you how many times I've had trouble with side-by-side versions of Visual Studio (e.g., 2013 + 2015 + 2017) all on one box causing really hard to troubleshoot problems. Or PATH environment variables causing VS to look at the wrong tool version for some add-in.
- VS add-ins: Resharper and other really heavy add-ins that modify VS behavior can sometimes cause weird things to happen.
- Display drivers: This is a weird one, but it's happened to me. VS doesn't always use "standard" Windows controls like dropdowns and things. Even if it looks standard, it's not always. They roll their own. I had a thing where the build configuration editor (the thing where you choose whether it builds Debug or Release and which platform it targets) wouldn't render if I had VS on a second monitor. It'd only work on the primary monitor. That's because the display drivers didn't want to render the control properly. Yeah, weird, but true.

If you clear your caches and it's still not working, I'd recommend asking the folks in the NuGet repo what's up. There's really nothing Swashbuckle can do about the tooling.

**Comment by daniloro** [comment] 2017-08-24 20:12
I discovery my problem.
The problem is related to ProGet [(http://inedo.com/proget)](url) a universal package manager for on premise repository.
ProGet cache remote feeds on local servers, and visual studio reads packages from local ProGet feed.

When I run the command "Find-Package Swashbuckle.AspNetCore" on Package Manager Console using ProGet feed I recive the error "Unable to find package 'Swashbuckle.AspNetCore'", but when I change feed to "https://www.nuget.org/api/v2" the package are installed successfuly.

In this way I believe this package is not get from "https://www.nuget.org/api/v2" and cached by ProGet. Other packages work on ProGet, around (1.979) used in local projects.

**Closed** 2017-08-25 15:32 UTC

**Comment by tillig** [comment] 2017-08-25 15:36
@daniloro You're using the NuGet v2 feed, which I believe is deprecated, or at least not being actively supported anymore. The NuGet v3 URL is `https://api.nuget.org/v3/index.json` - that might yield better results.
