### ISSUE TITLE
swagger.json not found with Azure Service Fabric applications

### ISSUE THREAD

**Issue by starklord07** [domaindrivendev/Swashbuckle.AspNetCore#857] opened 2018-08-20 14:13 UTC
I am really struggling to work Swagger with an Azure Service Fabric Cluster. We are working on Azure service fabric and we have a couple of SF applications. Each application type is having again a couple of services with it. Now we have integrated the Swashbuckle Swagger as : 

`            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("SwagService1", new Info { Title = "Something", Version = "v1.0" });
            });
`

`            app.UseSwagger(c => c.PreSerializeFilters
                .Add((swagger, httpReq) => swagger.Host = httpReq.Host.Value));

            app.UseSwaggerUI(c => c.SwaggerEndpoint("/AppName/ServiceName/swagger/SwagService1/swagger.json",
                "SwagService1"));
`

Also we have used an aggregated Swagger UI for all of our SF services across from different applications in a single service as follows ; 

`            var apiList = Configuration.GetSection("FromAppSettingsJson").Get<SettingsModel>();
            app.UseSwaggerUI(c =>
                apiList.APIListItems.ForEach(apiItem => c.SwaggerEndpoint(apiItem.EndpointUrl, apiItem.Name)));
`
and we have stored all the swagger endpoints configurations (the above ones) in this appsettings.json. 

This thing is working pretty good in my local service fabric cluster but after deploying to Azure SF, I am not able to access Swagger UI. I am getting the following error..

**Failed to load API definition**
Fetch error > swagger.json not found. 

However when I try to access individual service specific swagger.json then I am able to access swagger.json but again could not able to access SwaggerUI. 

Can anyone help me on this ?

**Comment by starklord07** [comment] 2018-08-21 10:46
@domaindrivendev I am not sure it is a CORS issue, when I try to access the Swagger UI, I get the following header and error 
![image](https://user-images.githubusercontent.com/18307876/44397303-8bc0a580-a55d-11e8-96fb-64700abe353b.png)

**Comment by domaindrivendev** [comment] 2018-08-24 22:05
@starklord07 - is the `Request URL` you've shown above correct? In other words - does it work when you access directly via browser?

**Comment by esbenbach** [comment] 2018-10-13 06:37
I have a similar SF setup and the issue we faced is that the swagger UI is served by accessing the reverse proxy while the service hosting that is not really aware so the url for the swagger.json is relative to the node serving the swagger ui anf not the reverseproxy, so in short it points to a path that does not exist when using the proxy.

**Comment by diegosasw** [comment] 2020-12-04 13:01
Having the same issue with a Service Fabric cluster. My local 1 node cluster does not have this problem. The Development or Qa cluster (5 nodes) has this `Not found` problem unable to fetch `/swagger/v1/swagger.json`
However I can see the json by using the absolute url (e.g: `https://mydevcluster:19008/MyProject/WebApi/swagger/v1/swagger.json ` so there must be something being done at the proxy with the Urls.

Is there anything in Swashbuckle to add prefix in swagger url? I have a similar issue with other things such as Hangfire where I must specify a PrefixPath such as `/MyProject/WebApi` when running in a multi node service fabric cluster.

If swashbuckle supports something similar I suspect the issue is that my swagger app "thinks" it's running under a different url and I need to instruct it to assume that is running behind a reverse proxy and add some prefix.

**Comment by esbenbach** [comment] 2020-12-04 13:24
I think I figured out what it is because I had a similar issue with AD authentication in a different service also on SF.
I never verified if it is the case with swashbuckle, but I guess its the same thing.....

You need to tell the stack that is sitting behind a proxy: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0

I ended up doing a variation on the following

```
// In the ConfigureServices(IServiceCollection services) method
       // Service Fabric Reverse Proxy Configuration
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardLimit = null;
                options.RequireHeaderSymmetry = false;
                options.KnownNetworks.Clear(); // This is not really that smart - we should probably add a list of known proxies/networks
                options.KnownProxies.Clear();
                options.ForwardedHeaders = ForwardedHeaders.XForwardedHost |
                    ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
```
and
```
// In the Configure(IApplicationBuilder app, IWebHostEnvironment env) method
app.UseForwardedHeaders();
            app.Use((context, next) =>
            {
                var fabricServiceName = Environment.GetEnvironmentVariable("Fabric_ServiceName"); // ex fabric:/AppName/ServiceName
                if (string.IsNullOrWhiteSpace(fabricServiceName))
                {
                    return next();
                }

                var fabricServiceUri = new Uri(fabricServiceName);
                var servicePathBase = fabricServiceUri.AbsolutePath; // ex /AppName/ServiceName
                context.Request.PathBase = new PathString(servicePathBase);
                return next();
            });
```

Its not as such pretty - but it works for the authentication issue I had that is very similar. 
I think a similar approach should work here...need to adjust it obviously.

**Comment by diegosasw** [comment] 2020-12-15 14:37
The solution was rather easy for a workaround. Not so easy for automation as per @esbenbach proper suggestion that path are tweaked at proxy level.
The following was sufficient.
```
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/MyProject/WebApi/swagger/v1/swagger.json", "My Scheduler"));
```

**Comment by diegosasw** [comment] 2020-12-16 08:07
@esbenbach as per your previous answer, I managed to have the Azure AD authentication (id_token) for my service under service fabric by adding ForwardedHeaders and by customizing the request's `PathBase` as you mentioned. Thanks

However this does only work when there is just one instance of the service in the service fabric cluster. If I deploy it to some environment with 3 instances, for example, I get a 500 error when AD issues the token and the POST return uri to `/oidc-signin` is called. I'm guessing it's again some error related to the fact that there is a proxy/load balancer and it does not know where to forward that token or which instance initiated the flow. Sorry for the sligthly off-topic but, did you happen to resolve that?

**Comment by esbenbach** [comment] 2020-12-16 12:48
@diegosasw Actually i didnt since the services in question where i have the OIDC signin I have only needed one instance of. I just tried scaling it and, immediately got an Exception: Unable to unprotect the message.State.

Presumably because the state was generated by a different node.

My guess would be that we need to wire up some external data protection stuff like described here (blobstorage):

https://stackoverflow.com/questions/53490663/asp-net-core-2-1-cookie-authentication-appears-to-have-server-affinity/53501066#53501066 

Or here (redis):
http://www.tugberkugurlu.com/archive/asp-net-core-authentication-in-a-load-balanced-environment-with-haproxy-and-redis

Or since we are in SF already
https://github.com/SoCreate/service-fabric-data-protection
https://github.com/MedAnd/AspNetCore.DataProtection.ServiceFabric

I have not tested anything, so just guessing here.....

@domaindrivendev pretty sure this entire thread is not related to a swashbuckle issue, so you can probably just close it.

**Closed** 2021-01-12 23:19 UTC
