### ISSUE TITLE
Regression when updating from v5 to v6 regarding nullable types

### ISSUE THREAD

**Issue by liesahead** [domaindrivendev/Swashbuckle.AspNetCore#2503] opened 2022-09-23 07:38 UTC
Upgrading from `v5.6.3` to `v6.2.3` (or `v6.4.0`, no difference) and generated schema is different now.

In `v5.6.3` it was

```JSON
"/api/Authentication/GetSomeData": {
    "get": {
      "tags": [
        "Authentication"
      ],
      "parameters": [
        {
          "name": "userId",
          "in": "query",
          "schema": {
            "type": "string",
            "nullable": true
          }
        },
        {
          "name": "token",
          "in": "query",
          "schema": {
            "type": "string",
            "nullable": true
          }
        }
      ],
    ...
    }
}
```

But now it's like this
```JSON
"/api/Authentication/GetSomeData": {
    "get": {
      "tags": [
        "Authentication"
      ],
      "parameters": [
        {
          "name": "userId",
          "in": "query",
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "token",
          "in": "query",
          "schema": {
            "type": "string"
          }
        }
      ],
    ...
    }
}
```

Question is, how to make all nullable properties to have that `"nullable": true` in the schema again?

Tried to use `options.SupportNonNullableReferenceTypes`, but it has no effect.

**Comment by domaindrivendev** [comment] 2022-11-15 15:29
This is by design in order to comply strictly with the OpenAPI spec because `nullable` doesn't make sense for query parameters. The relevant detail is [here](https://swagger.io/docs/specification/describing-parameters/) in the section entitled "Empty-Valued and Nullable Parameters":

> Note: nullable is not the same as an optional parameter or an empty-valued parameter. nullable means the parameter value can be null. Specific implementations may choose to map an absent or empty-valued parameter to null, but strictly speaking these are not the same thing.

So, when you're API description says a `query` parameter is `nullable`, it's stating that it can be sent with the value `null` as follows:

```
GET /api/Authentication/GetSomeData?userId=null
```

And, this is not the same as saying it can be omittied (`required: false`) or empty-valued (`allowEmptyValue: true`) as follows:

```
GET /api/Authentication/GetSomeData?
GET /api/Authentication/GetSomeData?userId=
```

Furthermore, if `userId=null` is sent, then ASP.NET Core will initialize the corresponding parameter to the string value "null" as opposed to null. So, it really makes no sense to describe query parameters as `nullable: true`.

**Comment by zhuhuanzi** [comment] 2022-11-18 14:45
Because when we use nswg to generate typescript code, there is too much difference between the two, which seems to be a bad upgrade, Although it is the specification of OpenAPI.

**Comment by zhuhuanzi** [comment] 2022-11-18 14:50
@liesahead  
You can solve the problem in the following ways: #2536
``` C#
services.AddTransient<ISchemaGenerator, XXXSchemaGenerator>();

```

**Comment by liesahead** [comment] 2023-01-31 08:55
@zhuhuanzi , didn't find an example with custom schema in referenced issue.

**Comment by MichelZ** [comment] 2023-03-20 07:57
We have tried to work around this problem by using a parameter filter:

```
public class SwaggerNullableParameterFilter : IParameterFilter
    {
        public void Apply(OpenApiParameter parameter, ParameterFilterContext context)
        {
            if (!parameter.Schema.Nullable &&
                (context.ApiParameterDescription.Type.IsNullable(out _) || !context.ApiParameterDescription.Type.IsValueType))
            {
                parameter.Schema.Nullable = true;
            }
        }
    }
```

```
 services.AddSwaggerGen(options =>
            {
                options.ParameterFilter<SwaggerNullableParameterFilter>();
                [....]
});
```

**Comment by martincostello** [comment] 2024-04-14 10:16
To make issue tracking a bit less overwhelming for the new maintainers (see #2778), I've created a new tracking issue to roll-up various nullability issues here: #2793.

We'll refer back to this issue from there and include it as part of resolving that issue, but I'm going to close this one to help prune the backlog.

**Closed by martincostello** 2024-04-14 10:16 UTC
Labels: responded
