### ISSUE TITLE
swagger UI is not responding.

### ISSUE THREAD

**Issue by mkprajeen** [domaindrivendev/Swashbuckle.AspNetCore#287] opened 2017-01-30 12:50 UTC
when I request for documentation UI browser is not responding my URL as follows. http://localhost:51250/swagger/index.html  
But I am able to generate the josn using /swagger/v1/swagger.json

Log attached.
[swaggerIssueLog.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/738924/swaggerIssueLog.txt)

**Comment by domaindrivendev** [comment] 2017-01-30 19:18
Could you share your Startup.cs - specifically where you wire up the Swagger JSON (_AddSwagger_) and swagger-ui (_AddSwaggerUi_) middleware.

**Comment by mkprajeen** [comment] 2017-01-31 05:59
I am using asp.net core 1.1  and Swashbuckle.AspNetCore  1.0.0-rc1
also attaching the startup.cs methods in attached text file
[startup.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/741200/startup.txt)

**Comment by chomique** [comment] 2017-02-15 16:53
I have the same issue. It seems that the request from the UI's JS for swagger.json is not completed for some reason. When I access the /swagger/v1/swagger.json i can see the JSON file no problem. I can see the UI issuing the request for the same resource and even the HTTP 200 reply coming back, but the response stream from the server looks like not closed and response is not completed.

ConfigureServices method:
```
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Lube Analyst Next Gen Api", Version = "v1" });
                c.CustomSchemaIds(type => type.FriendlyId(true));
            });
```

Configure method:
```
            app.UseSwagger();
            app.UseSwaggerUi(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Shell Lube Analyst Next Gen Api");
            });
```

**Comment by professorjoshua** [comment] 2017-03-27 18:04
I have the same issue where I can view the JSON object:
/swagger/v1/swagger.json
but when I try to view the Swagger UI, /swagger/, it says it is reading the JSON object.  The load takes a long time and then eventually says the web browser ran out of memory.  This is a simple app at the moment with only 18 APIs.

**Comment by professorjoshua** [comment] 2017-04-14 15:06
@domaindrivendev do you have any update on this issue?  
The call to the JSON object works fine: 
`http://localhost:50000/swagger/v1/swagger.json`
But when I try to access swagger, google runs out of memory:
`http://localhost:50000/swagger/index.html`

In the ConfigureServices method I have:
`            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "MM2.0 API", Version = "v1" });
                var filePath = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "MenuManager.API.xml");
                c.IncludeXmlComments(filePath);           
            });`

And in the Configure method I have:
`            //use Swagger to document the API calls
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "MM2.0 API V1");
            });`

I really need to get this up and running.  Any suggestions?

**Comment by domaindrivendev** [comment] 2017-04-14 15:43
Next steps would be understanding of this is a Swashbuckle issue or a swagger-ui (different project) issue. You should take the generated JSON, which SB creates, and run it through a Swagger validator. If it's valid then the issue is really with swagger-u and you should post there.

Might also be worth testing the same JSON in an independent version of swagger-ui (see that project for setup instructions)

**Comment by domaindrivendev** [comment] 2017-04-14 15:44
Btw the swagger-hi repo is here https://github.com/swagger-api/swagger-ui

**Comment by professorjoshua** [comment] 2017-04-14 20:37
@domaindrivendev Any suggestions on a Swagger validator that I can run on localhost?  

I'm using Swashbuckle.AspNetCore which includes Swashbuckle.AspNetCore.Swagger and Swashbuckle.AspNetCore.SwaggerUI.  Wouldn't that make it a SB issue.  :)

**Comment by domaindrivendev** [comment] 2017-04-15 01:13
Follow that dependency tree a little further ...

Swashbuckle.AspNetCore.SwaggerUi pulls in "swagger-ui" as a bower dependency.

Theres an online validator you can POST the Swagger JSON to. Don't have the details offhand but if you take a quick look in the IntegrationTests project (this repo), it uses it.

**Comment by professorjoshua** [comment] 2017-04-17 13:18
@domaindrivendev The validator I found returned the following:

`{"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"allOf","message":"instance failed to match all required schemas (matched only 0 out of 1)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/operation/properties/consumes"},"instance":{"pointer":"/paths/~1api~1security-groups/post/consumes"}}]}`

**Comment by professorjoshua** [comment] 2017-04-18 15:46
@domaindrivendev So I removed all but my basic APIs and was able to trace the error to my HttpPosts.  The problem is with the creation of the "definitions" in the swagger.json.  The moment I include an API with an HttpPost the size of the JSON explodes.  Some of my data models include ICollection of other data models.  Swashbuckler appears to be drilling down into these collections and creating definitions for the collections.  Is there a way to stop Swashbuckler from automatically drilling down into ICollections and only look at the primitive data types of my model?

**Comment by mkprajeen** [comment] 2017-04-19 13:11
why this ticket is closed. Issue is still not addressed.

**Comment by professorjoshua** [comment] 2017-04-19 13:37
@mkprajeen I'm guessing @domaindrivendev thought you and I were having the same issue.  I agree the issue should not be closed until we determine what is causing the problem.  

What I did to start trouble shooting my problem is to remove all the API's except for one basic API with just a HttpGet.  I confirmed that the end point worked and then confirmed that the Swagger Doc was created.  I then added the API's back in one by one and confirmed the end point and swagger doc.  Once I got to an API that broke the Swagger Doc I removed all methods from said API and added the methods back in one by one to determine which method was creating the issue.  

I found that the methods in my APIs that are causing the Swagger Doc to crash are my HttpPost.  Once I had a post with a method that accepts one of my Entity Framework (EF) models I found that Swashbuckler went through ALL the EF models and added definitions for them in the swagger.json.  This is now where I am stuck.  

I've tried a couple of different validation tools against the swagger.json that is being created by Swashbuckler but the output from those tools hasn't helped, yet.  I'm guessing there is an issue with the references inside the json definitions of the models but I haven't pinpointed the issue yet.  If you come across a solution then please pass it along.

**Comment by domaindrivendev** [comment] 2017-04-21 05:39
@professorjoshua thanks for taking the time to troubleshoot yourself. As someone providing a lot of personal time to this free and open source project, this is very helpful and much appreciated.

One thing to keep in mind with Swashbuckle is that it treats "code as truth". If your action accepts a complex type, then any public properties on that type, anywhere in it's inheritance hierarchy, will be included with the Swagger description unless they're explicitly decorated with the JsonIgnoreAttribute.

This reflects Core's model binding behavior. Although it may not be the "intended use" of your API, a consumer "can" set a value for those properties by including a corresponding field with the JSON payload. Regardless of SB, this is something people should be aware of when using types they don't control as model-bound parameters, as pointed out by Scott H [in this recent post](https://www.hanselman.com/blog/ASPNETOverpostingMassAssignmentModelBindingSecurity.aspx)

So, Swashbuckle doesn't provide a way restrict the properties that are described for an API type other than preventing them from actually being accepted - e.g. marking private/internal or decorating with JsonIgnoreAttribute. This is fundamental to SB - code (as opposed to intention) is truth and the ideal way to use it is for your code to reflect your intention, exactly. Hope this makes sense.

Finally, deeply nested public properties in your EF classes are likely causing the UI to crash.

**Comment by domaindrivendev** [comment] 2018-02-14 18:29
As described above, using EF classes for action parameters is strongly discouraged for a code-driven documentation tool like Swashbuckle because they contain many public properties that "can" be populated from a JSON payload even if that's not the developers intention. By design, SB is driven by what "can" be done as opposed to what's intended. Furthermore, these classes have complex dependency graphs that are clearly causing issues for the swagger-ui to render.

I know this isn't the best answer because I do appreciate the convenience of using EF classes as model-bound parameters. But, I'm not going to make changes to SB to better support them because that would conflict with the fundamental goal of SB - i.e. code-driven documentation. Therefore, I'm going to close this issue.

**Closed by domaindrivendev** 2018-02-14 18:29 UTC
Labels: waiting for response
