### ISSUE TITLE
param example attribute complex type support?

### ISSUE THREAD

**Issue by jongio** [domaindrivendev/Swashbuckle.AspNetCore#2107] opened 2021-04-27 05:04 UTC
v5.6.3

I'm trying to get an example to populate from <param example> to swagger UI

![image](https://user-images.githubusercontent.com/2163001/116187466-71f69980-a6da-11eb-9c95-f28b2deae20f.png)

```
/// <summary>
        /// asdfasdf
        /// </summary>
        /// <param name="id" example="1"></param>
        /// <param name="inputData" example="&#123;&quot;myDataId&quot;:&quot;1&quot;&#125;"></param>
        /// <returns></returns>
        [HttpPut("{id}")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<IActionResult> UpdateData(int id, MyData inputData)
```

With that encoded JSON it appears in my xmlcomments output file.
```xml
<member name="M:Webapi.Controllers.MyDataController.UpdateData(System.Int32,Webapi.Models.MyData)">
            <summary>
            asdfasdf
            </summary>
            <param name="id" example="1"></param>
            <param name="inputData" example="&#123;&quot;myDataId&quot;:&quot;1&quot;&#125;"></param>
            <returns></returns>
        </member>
```

But doesn't appear in Swagger.json

![image](https://user-images.githubusercontent.com/2163001/116187579-a66a5580-a6da-11eb-89c3-dac48fe42aa1.png)

Based on code here:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/95cb4d370e08e54eb04cf14e7e6388ca974a686e/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs#L79

It does look like it tries to ConvertFromJson

I also tried to define an example at the class level, but that didn't work either

![image](https://user-images.githubusercontent.com/2163001/116187931-5770f000-a6db-11eb-9e47-b34e9d248eb4.png)

azsdke2e
azsdke2e2
ddcc1

**Comment by bradygaster** [comment] 2021-04-28 14:50
Pinging @domaindrivendev - is there a workaround for this or a release in which you plan on resolving this? @jongio pinged me about this from the SDK team - was wondering if there's a way forward or if this is by design.

**Comment by domaindrivendev** [comment] 2021-04-28 16:45
So - there's a few things here. Firstly, when providing JSON object/array examples _via XML comments_ you need to use the following sytntax to workaround XML encoding issues:

```xml
<!-- for parameters -->
<param name="inputData" example='{ "myDataId": 125 }'></param>

<!-- for properties -->
<example>{ "myDataId": 125 }</example>
```

__However__ ... I've delved into the code and can see that while this works well for Open API `parameter` definitions, it is not currently implemented for OpenAPI `requestBody` definitions - a miss in the original implementation. I think I can add this and get a new release minted fairly quick. As it's so simple, I'm happy to knock it out now. Stay tuned.

**Comment by bradygaster** [comment] 2021-04-28 18:20
Thanks @domaindrivendev! Keep us posted.

**Closed** 2021-04-28 18:43 UTC

**Comment by domaindrivendev** [comment] 2021-04-28 18:50
@jongio that's all merged in - before I push to the official Nuget feed, could you possibly pull down the `6.1.4` preview from myget.org and ensure the syntax I outlined above now works for your usecase:

https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

**Comment by jongio** [comment] 2021-04-28 20:01
Awesome.  Testing now.

**Comment by jongio** [comment] 2021-04-28 20:06
Confirmed this works! 

Thank you so much for fixing that so quickly.

![image](https://user-images.githubusercontent.com/2163001/116465749-7f1ea000-a822-11eb-8f19-cbb9abd8cfb5.png)
