### ISSUE TITLE
Enum values not shows in 5.3.1

### ISSUE THREAD

**Issue by bynf** [domaindrivendev/Swashbuckle.AspNetCore#1622] opened 2020-04-14 14:58 UTC
Hi there,
I was update to Swashbuckle.AspNetCore 5.3.1 version. Then I realized that the enum values are not visible. 

![image](https://user-images.githubusercontent.com/20435571/79239058-cd137080-7e78-11ea-871e-3eb44299fef1.png)

At first i thought to open issue on swagger-ui repo. But 5.2.1 version is works for me. I think problem in 5.3.1 version.

Thanks,

**Comment by domaindrivendev** [comment] 2020-04-15 08:42
With some basic testing this does not repro for me. Could you please put together a minimal sample project that repro's the issue and post to github, where I can pull down and investigate further? Thanks

**Comment by bynf** [comment] 2020-04-15 20:10
I will try to send you a simple project.

**Comment by SarperMUTLUBAY** [comment] 2020-04-19 15:24
i have same issue and i reproduce in the sample repository that i created for #1627 please check issue in my repository

https://github.com/SarperMUTLUBAY/SwaggerUIBug

![image](https://user-images.githubusercontent.com/10811371/79691883-a2eff300-826a-11ea-9aeb-6cf837d97756.png)

**Comment by domaindrivendev** [comment] 2020-04-20 09:11
@SarperMUTLUBAY - thanks for the cross-reference. If you look closely at the screenshot provided by @bynf above you can see the weird `ı` character where a regular `i` should be to describe the schema type.

Now, I believe the two issues share the same root cause (likely an issue with the [swagger-ui library](https://github.com/swagger-api/swagger-ui) rather than SB itself) and so I'm going to close this one and continue tracking in #1627

**Closed by domaindrivendev** 2020-04-20 09:11 UTC
Labels: waiting for response
