### ISSUE TITLE
Maybe not handling DateOnly method parameters correctly?

### ISSUE THREAD

**Issue by cleames** [domaindrivendev/Swashbuckle.AspNetCore#2319] opened 2022-01-24 16:22 UTC
Hi,

Doing a .NET 6.0 solution in VS2022. Swashbuckle.AspNetCore 6.2.3 comes with it when you say you want OpenAPI documentation. One of the new features of C# 10 is being able to use DateOnly (and TimeOnly) fields, as compared to only having DateTime fields in the past. Passing in a DateTime to my test method on the Get, it works as expected:
![image](https://user-images.githubusercontent.com/93782097/150819329-f1d604f0-9c69-4a2f-bb9d-783d25d6efb8.png)

When trying a DateOnly, I see unexpected behavior:
![image](https://user-images.githubusercontent.com/93782097/150819502-65d97170-177d-4529-ace8-347c8f62efec.png)

My C# call for that looked like this:     public IActionResult Foo(DateOnly? param1).
If I change it to force it to take it from the query, meaning     public IActionResult Foo([FromQuery] DateOnly? param1)...I see this:
![image](https://user-images.githubusercontent.com/93782097/150819895-ebe3691d-ae66-4339-8061-bd924d11a797.png)

I was expecting a few things...
1. To not have to explicitly state to get it from the query.
2. To be able to enter a date only, not in parts, like we can do for datetimes.

Is this considered an issue, or does it work "as expected" and I'm just missing something here?

Thanks in advance for any thoughts on this!

**Comment by mmillican** [comment] 2022-03-01 07:00
There is a 3rd party contribution that handles this: https://github.com/maxkoshevoi/DateOnlyTimeOnly.AspNet#swagger-support. Would be nice though if it was built-in.

**Comment by pdevito3** [comment] 2022-05-06 14:29
also seeing this. thanks for linking the repo @mmillican, going to give that a whirl. agreed that it would be great to have this built in though

**Comment by DamianEdwards** [comment] 2022-08-06 00:28
Can also workaround by configuring Swashbuckle with a custom type mapping for `DateOnly`:

```c#
builder.Services.AddSwaggerGen(
    c.MapType<DateOnly>(() => new OpenApiSchema
    {
        Type = "string",
        Format = "date"
    });
);
```

**Comment by captainsafia** [comment] 2022-08-08 13:47
It seems that perhaps adding an explicit mapping here would do the trick:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/95cb4d370e08e54eb04cf14e7e6388ca974a686e/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs#L206

`TimeOnly` is also susceptible to this bug for the same reason and the same modification should do the trick.

@domaindrivendev Does the above seem like a sensible place for the fix?

**Comment by domaindrivendev** [comment] 2022-08-08 20:39
@captainsafia yep that would be the right place for Newtosoft. For STJ, which now also supports those types, you'll need to make a similar change here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs#L241

**Comment by ErroneousFatality** [comment] 2022-11-10 11:56
Since .Net 7 now supports json deserialization of DateOnly and TimeOnly objects, it would be a good time to get those two types supported on swashbuckle soon.

**Comment by vernou** [comment] 2022-11-14 09:45
.NET was just released and the API template with WeatherForecast use DateOnly. In SwaggerUI, the schema GET return is :
```json
[
  {
    "date": {
      "year": 0,
      "month": 0,
      "day": 0,
      "dayOfWeek": 0,
      "dayOfYear": 0,
      "dayNumber": 0
    },
    "temperatureC": 0,
    "temperatureF": 0,
    "summary": "string"
  }
]
```
But the response from the API is :
```json
[
  {
    "date": "2022-11-15",
    "temperatureC": 8,
    "temperatureF": 46,
    "summary": "Chilly"
  },
  ...
```
To reproduce, just create a new API in .NET 7 and run.

**Comment by domaindrivendev** [comment] 2022-11-14 12:55
Should be resolved by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2480

**Closed by domaindrivendev** 2022-11-14 12:55 UTC
Labels: p1
