### ISSUE TITLE
Newtonsoft's JObject and JArray treated as a string

### ISSUE THREAD

**Issue by pechkarus** [domaindrivendev/Swashbuckle.AspNetCore#1390] opened 2019-11-22 19:15 UTC
## VERSION

Swashbuckle.AspNetCore 5.0.0-rc4

## STEPS

* Create controller that accepts post  or get with 'FromBody' or `FromQuery` object that is `JObject` or `JArray`.
Controller method:
```c#
[HttpPost]
[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(JArray))]
public Task<ActionResult<JArray>> PostStuff([FromQuery] JObject path, [FromBody] JObject justObject)
{
    return Task.FromResult((ActionResult<JArray>)new OkObjectResult(new JArray()));
}
```
* Configure `app.UseSwagger(o => o.SerializeAsV2 = true);`
* Go to `/swagger/v1/swagger.json` 

## EXPECTED
Expected `JArray` becomes `array` and `JObject` - `object`:
```json
...
    "post": {
        "tags": [
          "Just"
        ],
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "path",
            "type": "object"
          },
          {
            "in": "body",
            "name": "justObject",
            "schema": {
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array"
            }
          }
        }
      }
...
```

## ACTUAL
All `JObject`, `JArray` entities are marked as `string`
```json
...
    "post": {
        "tags": [
          "Just"
        ],
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "path",
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "string"
            }
          }
        }
      }
...
```
## NOTES

1. This seems to be happening for both V2 and V3
1. Additional minor issue - body parameter name is ignored and called `body`

**Comment by gilzig** [comment] 2019-11-26 16:20
Hi,
I have also fallen into the same issue after upgrading from version 4.0.1, which is a show stopper for me for using this upgrade. 
A similar issue also occurs when using 'JContainer' (also treated as string).
Is there a workaround for this, or any estimation for a fix?
Thank you very much!!!

**Comment by hantunes-if** [comment] 2019-12-03 17:41
Hi,
I tried to reproduce this issue, so I added your Action to the [DynamicTypesController](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Controllers/DynamicTypesController.cs) in Basic WebSite Project and the swagger file it generated doesn't seem to have any issue. The result was the following:

```json
"/pechkarusTest": {
      "post": {
        "tags": [
          "DynamicTypes"
        ],
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "path",
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/definitions/JToken"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/JToken"
              }
            }
          }
        },
        "x-purpose": "test"
      }
    },
```

**Comment by gilzig** [comment] 2019-12-04 07:23
Hi,

I opened a new project and created a minimal code example. It still assigned "string" to the type.
Attached are the example project I created and the produced json configuration.

Project file (zipped):
[swagger.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/3920533/swagger.zip)

Json configuration (zipped):
[example.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/3920534/example.zip)

I am using VisualStudio 2017, and .Net Core 2.2.  Perhaps this creates the difference?

Thank you very much,
Gil

**Comment by jlouros** [comment] 2019-12-04 08:12
Hi @gilzig 

the .Net Core version might be the issue. On a existing project, I was using .Net Core 2.2 and Swashbuckle.AspNetCore 4.* and I had no issues at all. I'm now upgrading the  same project to .Net Core 3.0, as part the upgrade I had to grab the latest Swashbuckle.AspNetCore version (5.0.0-rc4) because it's the only version that is compatible with .Net Core 3.0. I noticed that there are a ton of serialization differences. Not necessarily bugs, but differences with the default configurations. Mainly because the Swashbuckle.AspNetCore now uses https://github.com/microsoft/OpenAPI.NET under the hood.

Due to what I previously explained, my assumption is:
- for .Net Core 2.2 apps use Swasbuckle.AspNetCore 4.*
- for .Net Core 3.0 apps use Swasbuckle.AspNetCore 5.*

but only @domaindrivendev can confirm

**Comment by gilzig** [comment] 2019-12-09 11:19
Hi all,
I tried the same sample project with VS2019, and updated what was necessary, but received the same issue. 
I think it is NOT related to .Net Core 2.2.
I think this is related to the Swasbuckle.AspNetCore 5.*.

Best,
Gil

**Comment by domaindrivendev** [comment] 2019-12-10 12:06
Changes are in master. Can preview by downloading latest preview from myget.org. Closing in on the official release

**Closed by domaindrivendev** 2019-12-10 12:06 UTC

**Comment by gilzig** [comment] 2019-12-11 11:58
Thank you very much for the quick update!
I tried running with the latest code.
For a JObject as an request Body, the result schema is of a JToken, which must be an array.
This might mean that the code will not work for a simple JObject type (which is not an array).

What do you think?

Thank you very much!
Gil

**Comment by gilzig** [comment] 2019-12-21 16:32
After some further testing, I saw the the nswag studio generated file for the JObject is converted to:
`System.Collections.Generic.IDictionary<string, JToken> body`
Instead of a simple Object...
This also breaks the code. 
In the past, this was accessed as an Object type, so is was automatically converted to Json.

Any update on this?

Thank you very much,
Gil

**Comment by eimerreis** [comment] 2020-05-25 21:17
Hi There, 

I'm also facing some issues with JTokens being an array type, when it comes to generate client code from the swagger definition

**Comment by gabomgp4** [comment] 2021-11-24 15:42
@eimerreis , I'm having the same problem when generating the client. Something about a recursive type definition. If possible, could you tell me if you fixed the problem and how?

**Comment by eimerreis** [comment] 2021-12-07 11:42
@gabomgp4 we only solved this by typing our property to an `object` instead of a `JToken` which is probably a bad solution
