### ISSUE TITLE
Filtering operations by permissions is not working anymore (v3.0.0)

### ISSUE THREAD

**Issue by andrecarlucci** [domaindrivendev/Swashbuckle.AspNetCore#815] opened 2018-07-16 18:09 UTC
We are using an DocumentFilter to filter out all methods that an user doesn't have authorization to use.

That was working fine in the version 1.0.0. We would add the bearer and the page would reload all the endpoints again, bringing all the methods that the user has permission to use according to the entered token.

I updated to 3.0.0 and this is no longer working. Swagger-UI is not reloading the operations after adding an api key, therefore the user can't see the endpoints protected by permissions.

If I reload the page after adding the token, all is lost (the token is not there anymore).

Also, the popup is not closing automatically after clicking "Authorize". No javascript erros are shown on the browser console.

How to accomplish endpoint filtering according to permission in version 3.0.0?

**Comment by domaindrivendev** [comment] 2018-07-17 02:05
I think this might be a duplicate of #786.

I see you posted a corresponding [issue] to the swagger-ui repo, which I think is the correct step. However, as you'll see from the comments I added to that issue, it's an independent project maintained by a completely different group of people and so you're issue needs to be described from the perspective of that project. You should take a look at my comments there and make sure I'm representing your issue accurately.

**Closed by domaindrivendev** 2018-07-17 02:05 UTC

**Comment by andrecarlucci** [comment] 2018-07-18 13:22
Hi Richard,
Thank you so much for the help and for rewriting my issue in a much better fashion.
Sorry about the mess.
Cheers.
