### ISSUE TITLE
Bug in .net core Type.GetEnumValues does generate wrong Swagger.json

### ISSUE THREAD

**Issue by SharpNoiZy** [domaindrivendev/Swashbuckle.AspNetCore#1605] opened 2020-03-29 19:51 UTC
Hi,

I use the Swashbuckle 5.2.1 release and have a big issue with the resulting Swagger.json and with the following Client Generation with NSwagStudio.

All caused by a .net core Framework bug in System.Type.GetEnumValues wich You use in NewtonsoftSerializerContractResolver->GetSerializerEnumValuesFor.

You can Test this very easy with your GenerateSchema_HonorsSerializerAttribute_StringEnumConverter UnitTest.
Replace the subject enum with System.Net.HttpStatusCode which we use in our WebApi.

The enum looks decompiled like this, You can see that in fact there are dublicate int values, but the entries have a different name!

```
public enum HttpStatusCode
  {
    Continue = 100, // 0x00000064
    SwitchingProtocols = 101, // 0x00000065
    Processing = 102, // 0x00000066
    EarlyHints = 103, // 0x00000067
    OK = 200, // 0x000000C8
    Created = 201, // 0x000000C9
    Accepted = 202, // 0x000000CA
    NonAuthoritativeInformation = 203, // 0x000000CB
    NoContent = 204, // 0x000000CC
    ResetContent = 205, // 0x000000CD
    PartialContent = 206, // 0x000000CE
    MultiStatus = 207, // 0x000000CF
    AlreadyReported = 208, // 0x000000D0
    IMUsed = 226, // 0x000000E2
    Ambiguous = 300, // 0x0000012C
    MultipleChoices = 300, // 0x0000012C
    Moved = 301, // 0x0000012D
    MovedPermanently = 301, // 0x0000012D
    Found = 302, // 0x0000012E
    Redirect = 302, // 0x0000012E
    RedirectMethod = 303, // 0x0000012F
    SeeOther = 303, // 0x0000012F
    NotModified = 304, // 0x00000130
    UseProxy = 305, // 0x00000131
    Unused = 306, // 0x00000132
    RedirectKeepVerb = 307, // 0x00000133
    TemporaryRedirect = 307, // 0x00000133
    PermanentRedirect = 308, // 0x00000134
    BadRequest = 400, // 0x00000190
    Unauthorized = 401, // 0x00000191
    PaymentRequired = 402, // 0x00000192
    Forbidden = 403, // 0x00000193
    NotFound = 404, // 0x00000194
    MethodNotAllowed = 405, // 0x00000195
    NotAcceptable = 406, // 0x00000196
    ProxyAuthenticationRequired = 407, // 0x00000197
    RequestTimeout = 408, // 0x00000198
    Conflict = 409, // 0x00000199
    Gone = 410, // 0x0000019A
    LengthRequired = 411, // 0x0000019B
    PreconditionFailed = 412, // 0x0000019C
    RequestEntityTooLarge = 413, // 0x0000019D
    RequestUriTooLong = 414, // 0x0000019E
    UnsupportedMediaType = 415, // 0x0000019F
    RequestedRangeNotSatisfiable = 416, // 0x000001A0
    ExpectationFailed = 417, // 0x000001A1
    MisdirectedRequest = 421, // 0x000001A5
    UnprocessableEntity = 422, // 0x000001A6
    Locked = 423, // 0x000001A7
    FailedDependency = 424, // 0x000001A8
    UpgradeRequired = 426, // 0x000001AA
    PreconditionRequired = 428, // 0x000001AC
    TooManyRequests = 429, // 0x000001AD
    RequestHeaderFieldsTooLarge = 431, // 0x000001AF
    UnavailableForLegalReasons = 451, // 0x000001C3
    InternalServerError = 500, // 0x000001F4
    NotImplemented = 501, // 0x000001F5
    BadGateway = 502, // 0x000001F6
    ServiceUnavailable = 503, // 0x000001F7
    GatewayTimeout = 504, // 0x000001F8
    HttpVersionNotSupported = 505, // 0x000001F9
    VariantAlsoNegotiates = 506, // 0x000001FA
    InsufficientStorage = 507, // 0x000001FB
    LoopDetected = 508, // 0x000001FC
    NotExtended = 510, // 0x000001FE
    NetworkAuthenticationRequired = 511, // 0x000001FF
  }
```

But if you use Type.GetEnumValues, this method will return
```
[0] = {HttpStatusCode} Continue
[1] = {HttpStatusCode} SwitchingProtocols
[2] = {HttpStatusCode} Processing
[3] = {HttpStatusCode} EarlyHints
[4] = {HttpStatusCode} OK
[5] = {HttpStatusCode} Created
[6] = {HttpStatusCode} Accepted
[7] = {HttpStatusCode} NonAuthoritativeInformation
[8] = {HttpStatusCode} NoContent
[9] = {HttpStatusCode} ResetContent
[10] = {HttpStatusCode} PartialContent
[11] = {HttpStatusCode} MultiStatus
[12] = {HttpStatusCode} AlreadyReported
[13] = {HttpStatusCode} IMUsed
[14] = {HttpStatusCode} MultipleChoices
[15] = {HttpStatusCode} MultipleChoices
[16] = {HttpStatusCode} MovedPermanently
[17] = {HttpStatusCode} MovedPermanently
[18] = {HttpStatusCode} Found
[19] = {HttpStatusCode} Found
[20] = {HttpStatusCode} SeeOther
[21] = {HttpStatusCode} SeeOther
[22] = {HttpStatusCode} NotModified
[23] = {HttpStatusCode} UseProxy
[24] = {HttpStatusCode} Unused
[25] = {HttpStatusCode} TemporaryRedirect
[26] = {HttpStatusCode} TemporaryRedirect
[27] = {HttpStatusCode} PermanentRedirect
[28] = {HttpStatusCode} BadRequest
[29] = {HttpStatusCode} Unauthorized
[30] = {HttpStatusCode} PaymentRequired
[31] = {HttpStatusCode} Forbidden
[32] = {HttpStatusCode} NotFound
[33] = {HttpStatusCode} MethodNotAllowed
[34] = {HttpStatusCode} NotAcceptable
[35] = {HttpStatusCode} ProxyAuthenticationRequired
[36] = {HttpStatusCode} RequestTimeout
[37] = {HttpStatusCode} Conflict
[38] = {HttpStatusCode} Gone
[39] = {HttpStatusCode} LengthRequired
[40] = {HttpStatusCode} PreconditionFailed
[41] = {HttpStatusCode} RequestEntityTooLarge
[42] = {HttpStatusCode} RequestUriTooLong
[43] = {HttpStatusCode} UnsupportedMediaType
[44] = {HttpStatusCode} RequestedRangeNotSatisfiable
[45] = {HttpStatusCode} ExpectationFailed
[46] = {HttpStatusCode} MisdirectedRequest
[47] = {HttpStatusCode} UnprocessableEntity
[48] = {HttpStatusCode} Locked
[49] = {HttpStatusCode} FailedDependency
[50] = {HttpStatusCode} UpgradeRequired
[51] = {HttpStatusCode} PreconditionRequired
[52] = {HttpStatusCode} TooManyRequests
[53] = {HttpStatusCode} RequestHeaderFieldsTooLarge
[54] = {HttpStatusCode} UnavailableForLegalReasons
[55] = {HttpStatusCode} InternalServerError
[56] = {HttpStatusCode} NotImplemented
[57] = {HttpStatusCode} BadGateway
[58] = {HttpStatusCode} ServiceUnavailable
[59] = {HttpStatusCode} GatewayTimeout
[60] = {HttpStatusCode} HttpVersionNotSupported
[61] = {HttpStatusCode} VariantAlsoNegotiates
[62] = {HttpStatusCode} InsufficientStorage
[63] = {HttpStatusCode} LoopDetected
[64] = {HttpStatusCode} NotExtended
[65] = {HttpStatusCode} NetworkAuthenticationRequired
```

You can see that there are dublicate values, which will be in your generated Swagger.json and will be dublicate in the generated C# by NSwagStudio, which is a compile issue.

My suggestion would be that you not rely on this .net core method, which sounds stupid, but maybe there are better Community implemantations out there?

**Comment by SharpNoiZy** [comment] 2020-03-29 20:10
Enum.GetNames(jsonContract.UnderlyingType) seems to deliver the correct values, but as strings.
Maybe you can somehow use that?

```
[0] = {string} "Continue"
[1] = {string} "SwitchingProtocols"
[2] = {string} "Processing"
[3] = {string} "EarlyHints"
[4] = {string} "OK"
[5] = {string} "Created"
[6] = {string} "Accepted"
[7] = {string} "NonAuthoritativeInformation"
[8] = {string} "NoContent"
[9] = {string} "ResetContent"
[10] = {string} "PartialContent"
[11] = {string} "MultiStatus"
[12] = {string} "AlreadyReported"
[13] = {string} "IMUsed"
[14] = {string} "MultipleChoices"
[15] = {string} "Ambiguous"
[16] = {string} "MovedPermanently"
[17] = {string} "Moved"
[18] = {string} "Found"
[19] = {string} "Redirect"
[20] = {string} "SeeOther"
[21] = {string} "RedirectMethod"
[22] = {string} "NotModified"
[23] = {string} "UseProxy"
[24] = {string} "Unused"
[25] = {string} "TemporaryRedirect"
[26] = {string} "RedirectKeepVerb"
[27] = {string} "PermanentRedirect"
[28] = {string} "BadRequest"
[29] = {string} "Unauthorized"
[30] = {string} "PaymentRequired"
[31] = {string} "Forbidden"
[32] = {string} "NotFound"
[33] = {string} "MethodNotAllowed"
[34] = {string} "NotAcceptable"
[35] = {string} "ProxyAuthenticationRequired"
[36] = {string} "RequestTimeout"
[37] = {string} "Conflict"
[38] = {string} "Gone"
[39] = {string} "LengthRequired"
[40] = {string} "PreconditionFailed"
[41] = {string} "RequestEntityTooLarge"
[42] = {string} "RequestUriTooLong"
[43] = {string} "UnsupportedMediaType"
[44] = {string} "RequestedRangeNotSatisfiable"
[45] = {string} "ExpectationFailed"
[46] = {string} "MisdirectedRequest"
[47] = {string} "UnprocessableEntity"
[48] = {string} "Locked"
[49] = {string} "FailedDependency"
[50] = {string} "UpgradeRequired"
[51] = {string} "PreconditionRequired"
[52] = {string} "TooManyRequests"
[53] = {string} "RequestHeaderFieldsTooLarge"
[54] = {string} "UnavailableForLegalReasons"
[55] = {string} "InternalServerError"
[56] = {string} "NotImplemented"
[57] = {string} "BadGateway"
[58] = {string} "ServiceUnavailable"
[59] = {string} "GatewayTimeout"
[60] = {string} "HttpVersionNotSupported"
[61] = {string} "VariantAlsoNegotiates"
[62] = {string} "InsufficientStorage"
[63] = {string} "LoopDetected"
[64] = {string} "NotExtended"
[65] = {string} "NetworkAuthenticationRequired"
```

**Comment by domaindrivendev** [comment] 2020-04-01 10:04
I tried your repro suggestion and am NOT seeing the duplicate string values as you've indicated. In fact, I wouldn't expect to either because the Swashbuckle code doesn't even leverage `Type.GetEnumValues` if a `StringEnumConverter` has been configured.

Given the duplicate values in `HttpStatusCode`, I would think it's a bad idea to use it in your API mode/DTO classes fullstop. Independent of Swashbuckle, if you wanted to serialize enums as int values rather than strings, then your API will return incorrect data in a number of cases.

With that said, I gather your intention is to serialize the values as strings and this should be OK so long as you're serilaizer is configured to do so. When I configure a `StringEnumConverter` in my test project, then I don't see the duplicate entries so I'm wondering if you're missing something in your serializer setup?

Outside of Swasbuckle, have you confirmed that your API does in fact return string values when these enums are serialized to JSON? If you've confirmed this, then we'll have to dig deeper and I would suggest creating a minimal project that repro's the issue and posting to github where I can pull down and repro for myself.

**Comment by SharpNoiZy** [comment] 2020-04-03 13:14
I'm sorry, I can't provide more and better feedback I already did. 
I named you the exact UnitTest in **your** solution, how you have to change it to get the result I describe.

If you did so and don't get the same result like me, I have no explanation for that.
Than my Jetbrains Rider is broken or so.

**Comment by domaindrivendev** [comment] 2020-04-06 09:36
As I said in my response above, you're suggestion (i.e. tweaking the unit test) DOES NOT repro for me. Furthermore, I asked you to confirm that your API does in fact return string values when these enums are serialized to JSON and you've completely ignored that request.

If you're not willing to dig any deeper yourself, then I'm going to close the issue.

**Closed by domaindrivendev** 2020-04-06 09:36 UTC
Labels: waiting for response
