### ISSUE TITLE
Nullable Reference types

### ISSUE THREAD

**Issue by gaboe** [domaindrivendev/Swashbuckle.AspNetCore#1848] opened 2020-10-02 08:26 UTC
Is there any effort to generate correct types for null reference types? 

For example:

    public class CommentDto
    {
        public int CommentID { get; set; }

        public int BusinessCaseID { get; set; }

        public int SenderID { get; set; }

        public string Text { get; set; } = string.Empty;

        public UserDto? Sender { get; set; }
    }

    public class UserDto
    {
        public UserDto()
        {
            Login = string.Empty;
            FirstName = string.Empty;
            LastName = string.Empty;
        }

        public int UserID { get; set; }

        public string Login { get; set; }

        public string? Phone { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public DateTime? LastSignInDate { get; set; }

        public string? AvatarUrl { get; set; }
    }

will be generated as:

![image](https://user-images.githubusercontent.com/19681823/94902189-117ee100-0498-11eb-8034-aed3c65a8cb3.png)

There are multiple problems in this generated code:

1. Every C# string either nullable or non-nullable is generated as nullable
2. Every object type either nullable or non-nullable is generated as non-nullable.

I saw some hacks/extensions like this #1487, but in my opinion, this is a pretty basic feature and should be implemented in this library.

Thank you for your answer.

**Comment by gaboe** [comment] 2020-10-12 05:55
Unfortunately, we have moved to [nswag](https://github.com/RicoSuter/NSwag). It works correctly and migration have taken us only a few hours.

**Comment by domaindrivendev** [comment] 2020-10-12 08:48
Thanks for the feedback, and sorry to see you go. For anyone else reading this thread, rest assured support for Nullable Reference Types is top of the list for Swashbuckle and something I hope to get out very soon.

**Comment by Zero3** [comment] 2020-11-04 17:18
(I think this issue is a duplicate of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1686)

**Comment by domaindrivendev** [comment] 2021-01-14 20:46
Closing because (as stated by @Zero3) this is a dup of #1686

**Closed by domaindrivendev** 2021-01-14 20:46 UTC
