### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by itbencn** [domaindrivendev/Swashbuckle.AspNetCore#2665] opened 2023-06-13 08:44 UTC
An unhandled exception occurred while processing the request.

VStudio：17.7.0-preview1.0
NETSDK：8.0.100-preview.4.23260.5

[GrpcService1.zip](https://github.com/dotnet/aspnetcore/files/11724058/GrpcService1.zip)

<img width="943" alt="Snipaste_2023-06-12_22-00-05" src="https://github.com/dotnet/aspnetcore/assets/42700064/48ce4470-ef60-4b31-b8ea-946a0066941d">

```
<PackageReference Include="Grpc.AspNetCore" Version="2.54.0-pre1" />
<PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.54.0-pre1" />
<PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="8.0.0-preview.4.23260.4" />
<PackageReference Include="Microsoft.AspNetCore.Grpc.Swagger" Version="0.8.0-preview.4.23260.4" />
<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.1" />
```

https://github.com/dotnet/aspnetcore/issues/48589#issuecomment-1588684386
https://github.com/dotnet/runtime/issues/87460

**Comment by Havunen** [comment] 2024-02-18 11:47
This might be fixed in DotSwashbuckle, can you test using it please.
https://github.com/Havunen/DotSwashbuckle
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

**Comment by Havunen** [comment] 2024-02-18 11:50
It seems to be dependency of Microsoft.AspNetCore.Grpc.Swagger :/

**Comment by martincostello** [comment] 2024-04-14 09:28
Closing as external, and also the repro is using pre-release versions.

Please open a new issue if you can reproduce this with stable versions _and_ you're certain the issue is with Swashbuckle and not an external dependency.

**Closed by martincostello** 2024-04-14 09:28 UTC
Labels: external
