### ISSUE TITLE
[Bug]: Error starting SwaggerUI, http 500

### ISSUE THREAD

**Issue by hancpavel** [domaindrivendev/Swashbuckle.AspNetCore#2905] opened 2024-05-16 15:38 UTC
### Describe the bug

When starting Swagger ui on latest 6.6.1 version, getting error:
Message: JsonTypeInfo metadata for type 'System.Boolean' was not provided by TypeInfoResolver of type 'Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIOptionsJsonContext'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically. The unsupported member type is located on type 'System.Object'. Path: $.AdditionalItems.
Full exception: System.NotSupportedException: JsonTypeInfo metadata for type 'System.Boolean' was not provided by TypeInfoResolver of type 'Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIOptionsJsonContext'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically. The unsupported member type is located on type 'System.Object'. Path: $.AdditionalItems.
 ---> System.NotSupportedException: JsonTypeInfo metadata for type 'System.Boolean' was not provided by TypeInfoResolver of type 'Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIOptionsJsonContext'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type type, IJsonTypeInfoResolver resolver)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.WriteStackFrame.InitializePolymorphicReEntry(Type runtimeType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter.ResolvePolymorphicConverter(Object value, JsonTypeInfo jsonTypeInfo, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteDataExtensionProperty(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJsonExtensionData(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---

### Expected behavior

To work well as on 6.5.0 version :)

### Steps to reproduce

Code is the same, when reverting nuGet module back to 6.5.0 everything works well.

### Swashbuckle.AspNetCore version

6.6.1

### .NET Version

6.0.29

**Comment by martincostello** [comment] 2024-05-16 15:39
Duplicate of #2884, which will be fixed by #2890.

**Closed by martincostello** 2024-05-16 15:39 UTC
Labels: bug

**Comment by martincostello** [comment] 2024-05-21 16:55
Thanks for reporting this issue - the fix is available in [Swashbuckle.AspNetCore 6.6.2](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.6.2).

**Comment by hancpavel** [comment] 2024-05-22 09:44
thanks, works as expected!
