### ISSUE TITLE
Enum summary does not work when supplied on the property

### ISSUE THREAD

**Issue by k290** [domaindrivendev/Swashbuckle.AspNetCore#2120] opened 2021-05-12 13:42 UTC
Consider the below model used for an API endpoint
```
    public class VideoEventCreateDto 

        /// <summary>
        /// Image Type desc
        /// </summary>
        [Required]
        public ImageType ImageFileType { get; set; }
    }
    
        [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ImageType
    {
        Jpeg,
        Png,
        Bmp,
    }
```
    
  No description tag comes through in the swagger.json. Similar issue with other xml comments like `<example>`
Swashbuckle version 6.1.4

It does however work if you supply it only on the enum:

```
    public class VideoEventCreateDto 


        [Required]
        public ImageType ImageFileType { get; set; }
    }
            /// <summary>
        /// Image Type desc
        /// </summary>
        [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ImageType
    {
        Jpeg,
        Png,
        Bmp,
    }
```

However, I think it would be an improvement to allow it to be supplied on the property, as this is more consistent with how XML comments work on other valuetypes such as datetime. You could have different XML comments depending on the use case.

Unfortunately, to be backward compatible, you may need to implement logic to say that if the XML is supplied on the property, then it takes precedence over what is supplied on the enum. Or some similar logic

**Comment by akshay-tr** [comment] 2021-12-03 07:46
Is there's any plan to fix this one.

**Comment by GuySerg** [comment] 2023-01-23 00:28
Is the optional setting `UseAllOfToExtendReferenceSchemas()` suitable for you? Try to apply this on the `SwaggerGenOptions` object. Look also at #1303

**Comment by jgarciadelanoceda** [comment] 2024-07-02 15:23
@k290 , have you tried with the addition of #2943 using Myget?
I have just tried a simple scenario and it seems to be working now, in case you find it's working you can close this issue

**Comment by jgarciadelanoceda** [comment] 2024-07-03 22:09
If it's part of a body then it's the expected behaviour, see #1403 for more information

**Closed** 2024-07-04 05:05 UTC
