### ISSUE TITLE
Add a parameter to create the output folder with Swashbuckle.AspNetCore.Cli

### ISSUE THREAD

**Issue by mcraiha** [domaindrivendev/Swashbuckle.AspNetCore#2667] opened 2023-06-13 18:00 UTC
When Swashbuckle.AspNetCore.Cli is used, it will fail if the output folder does not exist (e.g. tofile is **$(Build.ArtifactStagingDirectory)/documents/api.yaml** and we currently only have **$(Build.ArtifactStagingDirectory)**). It would nice to have a parameter that allows to create the full path if it does not yet exist (like **-p** with **mkdir**).

**Comment by Havunen** [comment] 2024-02-18 11:45
The con is that if the path is incorrect, which often happens with relative paths, then it creates that folder and puts the data into some weird folder location, I dont see this as important feature as it can be achieved with single liner terminal /cmd command

**Comment by martincostello** [comment] 2024-04-14 09:24
If we did anything here, I think it would be better to not have an option but just have the code do it:

```csharp
var directoryName = Path.GetDirectoryName(fileName);
if (!Directory.Exists(directoryName))
{
    Directory.Create(directoryName);
}
```

The above wouldn't handle recursive creation of subdirectories, but it would help.

**Comment by martincostello** [comment] 2024-04-14 10:28
Duplicate of #2352

**Closed by martincostello** 2024-04-14 10:28 UTC
Labels: help-wanted
