### ISSUE TITLE
Json Response formatter

### ISSUE THREAD

**Issue by CodearoundHub** [domaindrivendev/Swashbuckle.AspNetCore#1842] opened 2020-09-30 13:03 UTC
Hi, 

this is a response of the service using swashbuckle. I want to change the format of these decimal, in particula I want to avoid the scentific annotation and i want to specify the number of decimal place.

How do i do this ?

![image](https://user-images.githubusercontent.com/13586739/94688033-5803fc80-032d-11eb-9a64-97c3bfc587bd.png)

Note than if i call the service normally, witouth use swash the returned json in formatted correctly. 

![image](https://user-images.githubusercontent.com/13586739/94688588-1889e000-032e-11eb-8898-f9331d71d7b3.png)

**Comment by MikeBeaton** [comment] 2020-09-30 20:17
Hi - this is just a fellow user, but I think your service is returning the correct values, then swagger-ui is parsing them from the correctly formatted json into JavaScript numbers, correctly, then when swagger-ui displays the result to you, it's just using some kind of default formatting which'll be the same formatting it uses for any number (from any field, from any API response). So this isn't affecting the underlying json, and won't affect any program that connects to your service, it's just affecting how the returned results are *displayed* to you when you use swagger-ui to test the service.

**Comment by MikeBeaton** [comment] 2020-10-01 09:26
I was thinking this must be purely a '[swagger-ui](https://github.com/swagger-api/swagger-ui)' issue, and that you'd have to ask there, or even on StackOverflow.

But I did a little more research for you and I found this: https://stackoverflow.com/questions/44968026/how-can-i-denote-decimal-floating-point-in-swagger-specs

So it is possible to mark up the intended number of decimal places (in what looks to me like a rather nasty way!), in OpenApi.

I know that `Swashbuckle.AspNetCore` relies on the Microsoft OpenApi library, and that library does indeed support [`MultipleOf`](https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L79). But I've searched through all the code of `Swashbuckle.AspNetCore` and it doesn't support setting this property.

You could set it yourself, e.g. in a preserialization filter, and then you'd find out whether or not 'swagger-ui' respects it.

**Comment by CodearoundHub** [comment] 2020-10-01 09:34
Yes, this kind of solution has been tryed but not run. 

we have create a schema filter and also for the decimal type we set this attribute. 

Below the code

![image](https://user-images.githubusercontent.com/13586739/94792948-05344e80-03da-11eb-9382-01996c4d222d.png)

**Comment by MikeBeaton** [comment] 2020-10-01 09:36
Not run? You mean it didn't make any difference?

**Comment by MikeBeaton** [comment] 2020-10-01 09:45
I think you may be thinking about this the wrong way!

Here's another person with the same problem: https://stackoverflow.com/q/55122833/

I can see it's frustrating, if you care about the exact decimal representation, to not be able to see the exact decimal representation in the tool which you're using to test your API.

But how are you going to eventually use the JSON which is sent? Presumably you're consuming it in a JavaScript application and you're going to deserialize the API response into JavaScript objects. But in that case, your value of `"cardholder_rate_sell: 0.00000099` *is* going to deserialize to a JavScript *Number* - which is not the best place to hold it if you are concerned about absolutely accurately matching a certain *decimal* value (as mentioned in https://stackoverflow.com/q/44968026/ which I referenced already above) . If you care about representing decimals absolutely correctly, you should probably be looking into a decimal supporting library for JavaScript, and sending these values from your API as strings.

**Comment by CodearoundHub** [comment] 2020-10-01 09:49
No not run this solution.

Off course, this is a cosmetic issue but our customer opened a bug with us for this also if the correct json is returned. 
The api cannot be changed (the string type is not correct for us), but I can start to investigate to inject some js to manage this, but according to us this is not a "clean" solution

**Comment by MikeBeaton** [comment] 2020-10-01 10:01
Well at least run the solution that you haven't run, and see what happens!! But note that multipleOf is not really a clean solution either, as it may fail due to rounding errors. If you do care about *exact* decimal representations, then just using numbers is not actually a truly correct approach (even if you can't change it). Yes, I think you're definitely left with looking into modifying swagger-ui somehow, or else using client education. I mean, the value *is* correct, it is just that the tool you are using to allow the client to test the API doesn't know how the value is going to be used, and is just **displaying** it as a general purpose number!

**Comment by MikeBeaton** [comment] 2020-10-01 10:05
And note that swagger-ui *isn't* this project, it's another project, which is used by this project - so if you want to find out about whether and how you can change how numbers are formatted in swagger-ui, you probably need to ask again there. But I suspect you're never going to find a way to control the decimal formatting, field-by-field, because that isn't what's going on - JSON and swagger-ui are not dealing in decimals (in the strict sense of the word, which would apply e.g. if you were using a decimal library).

**Comment by domaindrivendev** [comment] 2020-10-01 12:24
Thanks @MikeBeaton for your comments. I agree that the swagger-ui is simply a consumer of your API that happens to be implemented in JavaScript and what you're seeing is native JSON-to-JavaScript serialization behavior.

I don't think there's anything that can be done on the Swashbuckle side so am going to close this issue. I think a post to the [swagger-ui project](https://github.com/swagger-api/swagger-ui) or stackoverflow is probably your best bet for a way around this but I wouldn't hold out much hope 😞

**Closed by domaindrivendev** 2020-10-01 12:24 UTC

**Comment by AlexsandroHonorato** [comment] 2024-10-02 21:05
I'm having the same problem.

swagger gives smaller decimal places than expected

Example Error:  "taxaCotacaoVenda": 1111.1234567890124,
Expected :  "taxaCotacaoVenda":  1111.123456789012345

**Comment by martincostello** [comment] 2024-10-02 21:08
Please create a new issue with a minimal reproducible example.
