### ISSUE TITLE
First Letter Lowercase

### ISSUE THREAD

**Issue by male110** [domaindrivendev/Swashbuckle.AspNetCore#829] opened 2018-07-26 02:32 UTC
the model:
public class User
{
 public string UserName{get;set;}
}
the Api
public bool XXX([FromBody]User u)
{
}
the doc
{
  "userName": "string"
}
The first letter is lowercase,i want it is upercase

**Comment by domaindrivendev** [comment] 2018-08-26 04:51
By design, Swashbuckle delegates to the configured `JsonSerializer` so that descriptions match actual behavior. If you're seeing properties described in camelCase then I suspect that's what your serializer is configured to do. In other words, if you were to retrieve a `User` resource from your API - I imagine the JSON that's returned will be in camelCase and not PascalCase.

So, if you want the docs to be camelCase, then I assume you want the _actual_ serialization (i.e. when invoking your API) to do the same. This can be done as follows:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddMvc()
        .AddJsonOptions(options =>
        {
            options.SerializerSettings.ContractResolver = new DefaultContractResolver();
        });
}
```

See https://codeopinion.com/asp-net-core-mvc-json-output-camelcase-pascalcase/ for more info

**Comment by domaindrivendev** [comment] 2018-09-05 01:03
Closing due to inactivity. Let me know if the above approach is insufficient, providing additional detail, and I can re-open if neccessary

**Closed by domaindrivendev** 2018-09-05 01:03 UTC
Labels: waiting for response
