### ISSUE TITLE
expected to parse large "long" numbers correctly

### ISSUE THREAD

**Issue by amro93** [domaindrivendev/Swashbuckle.AspNetCore#1861] opened 2020-10-11 01:15 UTC
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

Pre conditions:
1- create async api action,
2- return long number 9223372036754775808

steps:
1- open swagger ui
2- invoke the created api action endpoint

expected result:
 the returned value must be equals to 9223372036754775808 as a number

actual:
 the returned value is equals to 9223372036754776000
 screenshot is attached below

notes:
 1- the same happens with object props and arrays.
 2- the numbers are shown correctly on postman

![image](https://user-images.githubusercontent.com/34315258/95668126-e8cdaa00-0b6f-11eb-8793-3b57227691a1.png)

1. If it's not a bug report, feature request or PR, don't submit it here. Post to Stackoverflow instead.
2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).
3. For bug reports, specify the version your using and provide clear repro steps.

**Comment by domaindrivendev** [comment] 2020-10-19 22:40
I believe this to be a duplicate of #1842

**Closed by domaindrivendev** 2020-10-19 22:40 UTC
