### ISSUE TITLE
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0

### ISSUE THREAD

**Issue by klaudiusz-czapla** [domaindrivendev/Swashbuckle.AspNetCore#2585] opened 2023-01-11 20:08 UTC
I ran into an issue when I was trying to generate swagger.json file using <strong><ins>swashbuckle.aspnetcore.cli</ins><strong> in version <string><ins>6.5.0</ins></strong> on machine with .net sdk installed in both versions (6 and 7)

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
The located assembly's manifest definition does not match the assembly reference. (0x80131040) 
File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

dotnet --info:
```
PS C:\Users\my_user_name> dotnet --info
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.404 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

.csproj:
```
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
```

After uninstalling .net 7 sdk it started working properly. Compilation succeeded. swagger.json file were properly re-built. 
Putting global.json file didnt help much

**Comment by Meligy** [comment] 2023-01-12 09:26
I got the same problem also running on a .NET 6 project, but only when running on .NET 7 SDK.

My project is a .NET 6 project that I'm looking forward to upgrading to .NET 7 later. I have .NET 6 and 7 installed on the machines. And I have a `global.json` file to control the .NET SDK version rollover to .NET 7. Also I wanted to take advantage of slightly improved `dotnet watch` command in .NET 7 SDK even before I upgrade the actual project.

When the `global.json` version is allowed to roll over to .NET 7, `"rollForward": "latestMajor"`, it fails to work with the same error above.

When I set the version to only allow .NET 6 in `global.json`, like `"version": "6.0.202", "rollForward": "latestMinor"`, the generation seems to work fine.

So, the failing scenario is building .NET 7 SDK while targeting .NET 6 runtime.

**Comment by Meligy** [comment] 2023-01-12 09:50
To help testing, make sure that you run `dotnet clean` before every build, and also including the `--no-incremental` flag in the build command, like `dotnet build --no-incremental`.

**Comment by klaudiusz-czapla** [comment] 2023-01-12 12:43
@Meligy May I ask you where to put this global.json file you referred to ? Should it be the root project or solution directory ? For me it didn't help (placed in solution directory) but let me double check it.

**Comment by klaudiusz-czapla** [comment] 2023-01-12 13:47
@Meligy  I can confirm that your approach helped. I did sth like this and it started build without any problems.
```
dotnet new globaljson --sdk-version 6.0.404 --roll-forward latestMinor
```

Maybe I had wrong file name but after using this command I made sure that it is created properly.

**Comment by TobiasBreuer** [comment] 2023-01-19 10:01
I'm currently facing the same issue - my problem is, that I **have** to have the .Net 7 SDK in my `global.json` file, as I have two APIs in the solution, one for .Net 6 and one for .Net 7. So in order to build all projects (which works fine) I have to use version 7 of the SDK, but when generating the swagger for the .Net 6 API with the .Net 7 SDK and swashbuckle cli version 6.5.0 I will get this exact exception - so it seems that I either have to separate those two APIs into individual solutions (and repositories) or align both APIs to use either Net 6 or Net 7 in both, a mixture seems to not be possible.

**Comment by klaudiusz-czapla** [comment] 2023-01-19 10:52
@TobiasBreuer I would advise to try out to put global.json file in the project itself which requires "downgrade"

As I found somewhere dotnet is traversing filesystem to look for that file so I assume global.json file on the level of solution will be overwritten by the file in the project itself but this is only my assumption, not tested by me..
<em>The global. json file in the root of your project (or even in the root of your file system as the SDK will traverse the file system until it finds one) allows defining which version of the SDK to use.</em>

**Comment by softwareengineerofficial** [comment] 2023-02-20 07:55
Im getting the same error with a .net core API project using 6.0 SDK. I'm getting this error while publishing the project to azure which was working perfectly fine before updating VS to the latest version.

**Comment by aswinfrancis91** [comment] 2023-02-20 13:33
We are also facing same issue. We had projects targeting 5.0 but build with 7.0. Build runs fine when in release mode but in debug mode I get the same error because of post build script that tries to generate swagger json. I updated to 6.0 and still faced the problem. It only worked after adding global json as mentioned above.
I have another project that is in 6.0 and has the same setup done with post build swagger json generation. It still works fine. The difference I noticed is that when I build it uses msbuild from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe
whereas the solution I have issue with runs msbuild from C:\Program Files\dotnet\sdk\7.0.103\MSBuild.dll

**Comment by danielloganking** [comment] 2023-03-06 21:51
I too am encountering this error. I updated to the latest version of .NET 7 SDK such that i get

```sh
> dotnet --version
7.0.201
```

and while I have some old SDK versions hanging around according to `dotnet sdk check` there is nothing that should cause this error. Downgrading to `swashbuckle.aspnetcore.cli` version 6.4.0 works fine though. @eslamisepehr since you wrote 3d5159c07 do you have any ideas what could be causing this?

**Comment by capjan** [comment] 2023-04-28 14:45
```bash
> dotnet --version
7.0.203
```
is also affected and downgrading to `swashbuckle.aspnetcore.cli` 6.4.0 is still a workaround.

53 days later since @danielloganking question. Any news on 6.5.0?

**Comment by zahalzel** [comment] 2023-07-21 19:03
We have a scenario in Visual Studio Web Tools - configuring Power Platform on .NET Web API projects - where we install the Swashbuckle CLI as a local tool. This is a blocking issue for .NET 6 Web API projects, any word on whether this will be fixed in the next update?

**Comment by eslamisepehr** [comment] 2023-11-14 13:24
> I too am encountering this error. I updated to the latest version of .NET 7 SDK such that i get
> 
> ```shell
> > dotnet --version
> 7.0.201
> ```
> 
> and while I have some old SDK versions hanging around according to `dotnet sdk check` there is nothing that should cause this error. Downgrading to `swashbuckle.aspnetcore.cli` version 6.4.0 works fine though. @eslamisepehr since you wrote [3d5159c](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/3d5159c07a9449c71cdd372182a4f0165de0c172) do you have any ideas what could be causing this?

I have checked, and the issue is due to the use of different versions of .NET at runtime.

**Comment by danielloganking** [comment] 2023-11-16 01:11
> I have checked, and the issue is due to the use of different versions of .NET at runtime. 

Does this mean that even if I have _only_ the .NET 7 SDK installed and use it to run an app or project which targets `net6.0` and _not_ `net7.0` then `swashbuckle.aspnetcore.cli 6.5.0` will fail to load?

**Comment by Havunen** [comment] 2023-11-17 06:24
This fails too, I dont have .NET 7 installed.

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.417
 Commit:    04fde1d2e3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.417\

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.417 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\git\Hilma\Hilma\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download



Then after un

**Comment by Baertie** [comment] 2023-12-05 14:00
+1

**Comment by aronbierbaum** [comment] 2024-01-23 19:16
@eslamisepehr Is there a workaround besides downgrading to Swashbuckle 6.4.0?

**Comment by Havunen** [comment] 2024-01-31 05:46
I created a fork of this repository, because I couldn't wait for the maintainer. 
The fork is called DotSwashbuckle https://github.com/Havunen/DotSwashbuckle it only supports .NET 8 for now.

Change the csproj nuget reference 
```patch
-<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
+<PackageReference Include="DotSwashbuckle.AspNetCore" Version="1.0.2" />
```

Install the dotnet tool
```
dotnet tool uninstall --global Swashbuckle.AspNetCore.Cli
dotnet tool install --global --version 1.0.2 DotSwashbuckle.AspNetCore.Cli
```

1.0.2 is the first working version.

I am planning to maintain that repository at least until this repository picks up with the development, so if you are interested using it you can post issues or open PRs there.

**Comment by martincostello** [comment] 2024-04-14 09:02
I'm going to close this in favour of #2792, as going through triaging the open issues I'm spotting a common theme and it's easier to manage one issue. Please track that issue for further updates.

If this issue isn't resolved once we have added support for `net8.0`, please open a new issue.

**Closed by martincostello** 2024-04-14 09:02 UTC
