### ISSUE TITLE
Add support to set BaseURL

### ISSUE THREAD

**Issue by jluqueba** [domaindrivendev/Swashbuckle.AspNetCore#441] opened 2017-07-05 11:33 UTC
Plase add support in EnableSwagger() to can be able to set BaseUrl in order to change URL use by Try It Out Button.

**Comment by kierenj** [comment] 2017-07-24 11:27
Dupe of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/427 ?

**Comment by vebaspect** [comment] 2017-08-10 11:04
+1

**Comment by JDL440** [comment] 2017-09-15 00:07
I was able to make this work by seeting the basePath like this:
.UseSwagger(c =>
{
c.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/MyServiceApp/MyService");
})

**Closed** 2018-06-08 07:31 UTC

**Comment by wswind** [comment] 2020-04-29 02:59
> I was able to make this work by seeting the basePath like this:
> .UseSwagger(c =>
> {
> c.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/MyServiceApp/MyService");
> })

swaggerDoc.BasePath is not working with  swashbuckle.aspnetcore version 5.3.3. How to fix this now?
