### ISSUE TITLE
Memory Leak when using a generic wrapper class 

### ISSUE THREAD

**Issue by Skyppid** [domaindrivendev/Swashbuckle.AspNetCore#2079] opened 2021-04-08 10:04 UTC
In order to detect whether parameters of a request were invalid, not set or valid, we need to wrap our primitive data types into another class since nullable types only tell us if it's valid or invalid but not whether it was actually left blank or was invalid.

So we created this class which wraps types and allows us to set meta data when parsing them via ModelBinder / Newtonsoft JSON, so we can tell what actually happened and return meaningful error messages.

But when using this class, Swashbuckle seems to run into a memory leak. We could nail it down to the `Exception` property. It seems that Swashbuckle cannot handle the recursive nature of `Exception` types. We could not find any way to ignore that property. Furthermore we need to change the generated schema for these types so they are exposed as their generic argument `T` type instead of the full `RequestParameter<T>` type. But the filters don't even get called, so we can't remove the Exception property there.

```csharp
    public sealed class RequestParameter<T>
    {
        public RequestParameter(string providedValue, Exception exception)
        {
            // Exception = exception;
            IsValid = false;
            RawValue = providedValue;
            Value = default(T);
        }
        
        public RequestParameter(string providedValue, T value)
        {
            Value = value;
            IsValid = true;
            RawValue = providedValue;
        }

        /// <summary>
        /// The underlying parameter value.
        /// </summary>
        public T Value { get; }
        
        /// <summary>
        /// The flag indicating, whether or not the parameter was provided in a valid format.
        /// </summary>
        public bool IsValid { get; }
        
        /// <summary>
        /// The raw parameter provided by the service consumer as a string.
        /// </summary>
        public string RawValue { get; }

        /// <summary>
        /// The exception that occurred while trying to parse the raw parameter value.
        /// </summary>
        [JsonIgnore]
        public Exception Exception { get; }
    }
```

With this sample controller I end up with memory ramping up beyond 26 GB until failure when I open the swagger UI:
```csharp
        [HttpGet("{bullshit}")]
        public async Task<ActionResult> Get([FromRoute] RequestParameter<Guid> param1, [FromBody] TransactionBody<Body> param2)
        {
            return Ok();
        }
```

Is there a way to ignore that property for Swashbuckle? JsonIgnore does not work here.

Thanks!

**Comment by domaindrivendev** [comment] 2021-04-08 10:36
This looks to be a dup of #1894. Swashbuckle 100% honors the `[JsonIgnore]` attribute but I have a feeling the recursive issue is actually occurring in ASP.NET Core's `ApiExplorer` code, before Swashbuckle takes over.

**Comment by domaindrivendev** [comment] 2021-04-08 11:01
I've confirmed this is 100% a duplicate of the referenced issue and can be repro'd using `ApiExplorer` on it's own independently of Swashbuckle. It needs to be fixed upstream. However, there is a workaround that might work for you - if you change the access modifier of your `Exception` property to `internal`, which kind of makes sense if you think about it, then ApiExplorer will ignore it and you'll avoid the memory issue.

**Closed** 2021-04-08 11:02 UTC

**Comment by Skyppid** [comment] 2021-04-08 11:50
Thanks @domaindrivendev  for the fast reaction. That's good to know and a great tip. Solved our issue.
