### ISSUE TITLE
serializerPropertyMetadata newslot flag , and newslot property will be throw exception

### ISSUE THREAD

**Issue by hemiaoio** [domaindrivendev/Swashbuckle.AspNetCore#1594] opened 2020-03-25 04:34 UTC
I have a property that is overridden based on the base class, but the type is different. Then I used the `new` keyword. When generating swagger, Swashbuckle threw an Exception that already exists in the Key.

DtoBase Code
``` csharp
public class DtoBase{
     ....other code
     public BaseType Detail{get;set;}
     ....other code
}
```

SubClass Code
``` csharp
public class Dto : DtoBase {
    ...other code
    public new DetailType Detail {get;set;}
    ...other code
}
```

```
ArgumentException: An item with the same key has already been added. Key: detail
System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey key, TValue value)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator+<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, string schemaId, Func<OpenApiSchema> factoryMethod)
```

**Comment by domaindrivendev** [comment] 2020-03-25 18:58
This is likely a dup of #1428 (same root cause at least) which now has a fix merged into master

**Closed by domaindrivendev** 2020-03-25 18:58 UTC
