### ISSUE TITLE
[Bug]: Failed to generate schema for models with dictionary base occured in 6.7.2

### ISSUE THREAD

**Issue by maantoszyk** [domaindrivendev/Swashbuckle.AspNetCore#3118] opened 2024-10-24 11:43 UTC
### Describe the bug

**Issue:**
When moving from version 6.7.1 to 6.7.2 there is an issue where the schema for swagger fails to generate and the http status code Internal Server Error is returned.
The problem from exception is: _Expected Dictionary to have two generic type arguments but it had 1._

**Background:**
I am using several base models for API models which is probably causing the problem. One of them is based on the dictionary type. I've been using them since version 5.4.1 without any issues.

**Tried:**
I tried updating to the latest current version 6.9.0 but it still doesn't fix the issue.

**Example:**
I made a minimalistic example using my base models to demonstrate the problem. When you downgrade to <6.7.2 it should work.

### Steps to reproduce

https://github.com/maantoszyk/swagger-bug-report

### Exception(s) (if any)

```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - DictionaryIssueMinimalExample.Controllers.CategoryController.Get (DictionaryIssueMinimalExample). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - System.Collections.Generic.IEnumerable`1[DictionaryIssueMinimalExample.Models.CategoryModel]. See inner exception
 ---> System.InvalidOperationException: Expected Dictionary to have two generic type arguments but it had 1. Member: DictionaryIssueMinimalExample.Models.Base.LocalizedEntityModel`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[DictionaryIssueMinimalExample.Models.CategoryLocalizationModel, DictionaryIssueMinimalExample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Localization Type: DictionaryIssueMinimalExample.Models.Base.LocalizationModel`1[[DictionaryIssueMinimalExample.Models.CategoryLocalizationModel, DictionaryIssueMinimalExample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
   at Swashbuckle.AspNetCore.SwaggerGen.MemberInfoExtensions.IsDictionaryValueNonNullable(MemberInfo memberInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass13_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateArraySchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass13_0.<GenerateConcreteSchema>b__1()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(Type modelType, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass40_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository, Func`3 operationsGenerator)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Swashbuckle.AspNetCore version

6.7.2

### .NET Version

.NET 8

### Anything else?

![swagger-error](https://github.com/user-attachments/assets/ecf9b330-fd3f-4ec5-adf5-676bacc3346b)

**Comment by martincostello** [comment] 2024-10-24 12:31
Issue is due to this check:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/da07a5356b6f65403a1405bca8e806e5e59733de/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs#L88

Which isn't handling [this type](https://github.com/maantoszyk/swagger-bug-report/blob/498004922fa3efbe31b1d530dd45fb0e39c15eca/DictionaryIssueMinimalExample/Models/Base/LocalizationModel.cs#L6):

```csharp
public class LocalizationModel<TLocalization> : Dictionary<string, TLocalization>;
```


This is essentially a duplicate of #3070. See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3070#issuecomment-2348268603.

**Closed by martincostello** 2024-10-24 12:31 UTC
Labels: bug
