### ISSUE TITLE
Swagger Docu doesn't shows example values

### ISSUE THREAD

**Issue by tualatin** [domaindrivendev/Swashbuckle.AspNetCore#2654] opened 2023-05-25 13:24 UTC
Create a OpenAPI spec, add a simple property like this

```
[...] 
    testProperty:
      description: For test only
      type: string
      example: Test-Test-Test
[...]
```

Start the latest openapi generator 2.6.0 (6.6.0) and let create the C# code. Take a look into the created class, you will find this

```
[...]
/// <sumary>
/// For test only
/// </sumary>
/// <value>For test only</value>
/// <example>&quot;Test-Test-Test&quot;</example>
[DataMember(Name="testProperty", EmitDefaultValue=false)]
public string TestProperty { get; set; }
[...]
```

Start your application and take a look into your swagger doc. The example value is ignored! When you remove the "\&quot;" from the example XML comment, than the example value is available.

The example value should shown, when the text is in &quot; parts.

**Comment by dldl-cmd** [comment] 2023-10-07 11:39
Duplicate of #2088

**Closed** 2024-04-14 09:34 UTC
