### ISSUE TITLE
Description for "FromForm" variables

### ISSUE THREAD

**Issue by thiagoknop3** [domaindrivendev/Swashbuckle.AspNetCore#2124] opened 2021-05-20 12:11 UTC
currently the descriptions for the "FromForm" parameters are not being generated in the swagger.json document.

SwashBuckle.AspnetCore version 6.1.3

**Comment by jacobjmarks** [comment] 2021-11-12 00:20
Duplicate of #2062

**Comment by martincostello** [comment] 2024-05-04 15:27
Duplicate of #2062

**Closed by martincostello** 2024-05-04 15:27 UTC
