### ISSUE TITLE
Using [AsParameters] annotation in minimal api does not lift summary comments of the model

### ISSUE THREAD

**Issue by andreasuvoss** [domaindrivendev/Swashbuckle.AspNetCore#2658] opened 2023-05-31 13:29 UTC
Swashbuckle.AspNetCore: 6.5.0
.NET 7

I am not sure if this is a bug or a feature request.

When defining APIs using the minimal API approach, the summaries from models are not lifted from the XML documentation and put into the resulting `swagger.json` like I would expect. Before migrating to minimal API we used controllers, and the `[FromQuery]` annotation in a similar way. This gave the expected result. However `[FromQuery]` is not supported when using minimal API, instead the `[AsParameters]` annotation was [added in .NET 7 ](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0#asparameters-attribute-enables-parameter-binding-for-argument-lists).

The summaries are present in the XML file generated when building the project, but not in the  `swagger.json` file.

I have created a minimal example showing that the summaries are not present (in both  `swagger.json` or SwaggerUI) when using the  `[AsParameter]` annotation, but they are included in the schema on the post request using the `[FromBody]` annotation.

I have a very ugly workaround using the  `WithOpenApi` extension method from the NuGet package `Microsoft.AspNetCore.OpenApi` to add descriptions to the individual indices of each parameter by modifying the mapping from my minimal example like so:
```csharp
app.MapGet("/AsParameters", ([AsParameters] AsParametersArgument request) => "Hello World!")
    .WithOpenApi(operation =>
    {
        operation.Parameters[0].Description = "Parameter one description";
        operation.Parameters[1].Description = "Parameter two description";
        return operation;
    });
```

### Minimal example: 

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    </ItemGroup>

</Project>
```

Program.cs:
```csharp
using System.Reflection;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    var assemblyName = Assembly.GetExecutingAssembly().FullName?.Split(',')[0];
    options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, $"{assemblyName}.xml"));
});

var app = builder.Build();

app.MapGet("/AsParameters", ([AsParameters] AsParametersArgument request) => "Hello World!");

app.MapPost("/FromBody", ([FromBody] FromBodyArgument request) => "Hello World!");

app.UseSwagger();
app.UseSwaggerUI();

app.Run();

internal struct AsParametersArgument
{
    /// <summary>
    /// This is a property with the number one - This is nowhere in SwaggerUI
    /// </summary>
    public string PropertyOne { get; set; }

    /// <summary>
    /// This is a property with the number two - This is nowhere in SwaggerUI
    /// </summary>
    public string PropertyTwo { get; set; }
}

internal struct FromBodyArgument
{
    /// <summary>
    /// This is a property with the number eight (this description is present in Swagger)
    /// </summary>
    public string PropertyEight { get; set; }

    /// <summary>
    /// This is a property with the number nine (this description is present in Swagger)
    /// </summary>
    public string PropertyNine { get; set; }
}
```

**Comment by codelovercc** [comment] 2023-06-05 13:56
> I think I'm running in to a similar issue. I'm trying to set a `boolean` parameter to show as NOT required in Swagger UI. It seems the model property attributes dont flow up
> 
> I have the following:
> 
> ```
> app.MapGet("/", ([AsParameters] GetRequestModel request) => "Hello World!");
> 
> public class GetRequestModel
> {
>     [FromQuery(Name = "unassigned_only")]
>     [JsonPropertyName("unassigned_only")]
>     [SwaggerParameter(Description = "Property description", Required = false)]
>     [DefaultValue(false)]
>     public bool UnassignedOnly { get; set; }
> }
> ```
> 
> The `DefaultValue` is displayed on Swagger UI fine, but the `SwaggerParameter` seems to have no effect. The `Description` isnt displayed on the Swagger UI and the parameter also still shows as "Required". I also tried using `SwaggerSchema` attribute, but same result.

Try change type `bool`  to `bool?`, then enable nullable reference type for project and Swashbuckle.AspNetCore

**Comment by codelovercc** [comment] 2023-06-11 08:02
@mr-davidc Welcome, I'm happy to help.
In my case, with project nullable enabled `<Nullable>enable</Nullable>`, and 
```csharp
       services.AddSwaggerGen(options =>
        {
            options.SupportNonNullableReferenceTypes();
        });
```

```csharp
public class MyDto
{
    public bool Encrypted {get;set;}
}
```

`MyDto.Encrypted` will be optional on the Swagger UI.

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/20984278/370fb8b9-63a0-4734-b73f-c44fac6d431e)

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/20984278/d17f5458-f7be-44ba-82cc-463c0a91e2ca)

**Comment by mr-davidc** [comment] 2023-06-25 23:01
Hi again @codelovercc,

I tried those options you mentioned above, but still my `bool` properties come through to Swagger UI as required. I really think the `[AsParameters]` is having an impact here.

I also still have an issue where the endpoint Summary doesn't come through to Swagger UI either, UNLESS I set `.WithOpenApi()` but then I lose all of my `SwaggerParameter` descriptions...

```
public static RouteGroupBuilder GetItemsRoute(this RouteGroupBuilder routeGroupBuilder)
{
    routeGroupBuilder
        .MapGet("/", GetItems)
        .WithSummary("Retrieve a list of items")                    <------- This doesnt display on Swagger UI
        .ProducesProblem(StatusCodes.Status400BadRequest)
        .ProducesProblem(StatusCodes.Status500InternalServerError);

    return routeGroupBuilder;
}
```

Any other things I can try to fix either of these issues?

**Comment by kaloyantihomirov** [comment] 2023-08-26 12:05
Hi! I want to share my experience as well. I'm also using the data annotation [AsParameters] to bind to an object. The `SwaggerParameter` seems to have no effect in the Swagger UI.

```
record Fruit(string Name, int Stock);

record struct CreateFruitModel
    ([FromServices] LinkGenerator Links,
    [FromRoute]
    [SwaggerParameter(Description = "The id of the fruit that will be created", Required = true)] string Id,
    [FromBody] Fruit Fruit);
```

```
app.MapPost("/fruit/{id}", handler.CreateFruit)
    .WithName("CreateFruit");
```
```
internal class FruitHandler
{
    private readonly ConcurrentDictionary<string, Fruit> _fruit;

    public FruitHandler(ConcurrentDictionary<string, Fruit> fruit)
    {
        _fruit = fruit;
    }

    /// <summary>
    /// Creates a fruit with the given ID, or returns 400 if a fruit with the given ID exists
    /// </summary>
    /// <param name="model">A model for the parameters we need to create a fruit</param>
    /// <response code="201">The fruit was created successfully</response>
    /// <response code="400">A fruit with the given ID already exists in the dict</response>
    /// 
    [ProducesResponseType(typeof(Fruit), 201)]
    [ProducesResponseType(typeof(HttpValidationProblemDetails), 400, "application/problem+json")]
    [Tags("fruit")]
    public IResult CreateFruit([AsParameters] CreateFruitModel model)
     => _fruit.TryAdd(model.Id, model.Fruit)
            ? TypedResults.Created(
                model.Links.GetPathByName("GetFruitById", new { model.Id })
                    ?? "N/A",
                model.Fruit)
            : Results.ValidationProblem(new Dictionary<string, string[]>
            {
                { "id", new[] { "A fruit with this id already exists" } }
            });
}
```

This is the only thing that I have found to work:
```
app.MapPost("/fruit/{id}", handler.CreateFruit)
    .WithName("CreateFruit")
    .WithOpenApi(o =>
    {
        o.Parameters[0].Description = "The id of the fruit that will be created";

        return o;
    });
```
It's not really clear for me which parameters do we access with o.Parameters. Here it seems that the collection contains only one parameter: the route id parameter.

**Comment by BoasHoeven** [comment] 2023-12-19 13:50
Seems like this feature is still missing, anyone know?

**Comment by jgarciadelanoceda** [comment] 2024-06-22 08:16
Hi @andreasuvoss , can you test if this is solved with the addition of #2943.
You can download the latest bits using myfeed.
I think that the PR has just done it

**Comment by jgarciadelanoceda** [comment] 2024-06-22 15:35
Reviewing this item a bit further I think that you did not use the EnableAnnotations extension method that comes from the nuget package Swashbuckle.AspNetCore.Annotations.
Unfortunuately if you apply it it throws an error that is only present for this specific scenario. I have got it and soon I will write a PR for this matter

**Comment by andreasuvoss** [comment] 2024-06-23 12:35
I’m not at my computer at the moment, I will try to test this sometime next week, maybe already tomorrow.

Med venlig hilsen / Best regards
Andreas Voss

På søn., 23 jun., 2024 kl. 14:18, Javier García de la Noceda Argüelles ***@***.***(mailto:På søn., 23 jun., 2024 kl. 14:18, Javier García de la Noceda Argüelles <<a href=)> skrev:

**Comment by andreasuvoss** [comment] 2024-06-23 12:37
> Hi @andreasuvoss, can you test if this is solved with the addition of #2943. You can download the latest bits using myGet. I think that the PR has just done it

I’m not at my computer at the moment, I will try to test this sometime next week, maybe already tomorrow.

**Comment by jgarciadelanoceda** [comment] 2024-06-26 19:53
Hi @andreasuvoss, reviewing the issues with MinimalApi, the issue is that if you use AsParameters the ContainerType is not present over the Parameters of the endpoint(The AsParametersArgument class is missing).
I think that we cannot do anything (Let me review it later), apart from recommending you to use the SwaggerParameter attribute

**Comment by jgarciadelanoceda** [comment] 2024-06-27 17:37
Hi @martincostello, I wasn't able to get the XML parameters to work when they are members of a AsParameters request.
It's a limitation on the OpenApi provider that Swashbuckle uses under the hood. Should we create an issue in their GitHub repo or as it's supported with the Attributes, it's at least covered

**Comment by martincostello** [comment] 2024-06-28 07:29
Sure, that sounds sensible.

**Comment by jgarciadelanoceda** [comment] 2024-08-20 19:03
It will be supported in dotnet10.

**Comment by martincostello** [comment] 2024-09-30 08:51
Closing as external.

**Closed by martincostello** 2024-09-30 08:51 UTC
Labels: upstream-openapi-dotnet, upstream-aspnetcore
