### ISSUE TITLE
[Bug]: Version 7.0.0 does not allow upgrading to .NET 9

### ISSUE THREAD

**Issue by raffaeler** [domaindrivendev/Swashbuckle.AspNetCore#3145] opened 2024-11-14 08:29 UTC
### Describe the bug

I tried to update the packages of a solution to .NET 9 and this is the result:

![image](https://github.com/user-attachments/assets/28a9192b-53f8-41e9-94d9-2bf0e9a4b075)

### Expected behavior

Updating to .NET 9 should be possible

### Actual behavior

(see picture)

### Swashbuckle.AspNetCore version

7.0.0

### .NET Version

9.0.100

**Comment by martincostello** [comment] 2024-11-14 09:08
I'm pretty sure this isn't a Swashbuckle issue, but is some fallout of the fact you're trying to use a preview of Microsoft.OpenApi v2:

![image](https://github.com/user-attachments/assets/4e816655-278d-4f72-937f-83bf6edbebb5)

Swashbuckle.AspNetCore is compiled against 1.6.22 and we have no maximum version constraints:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/be0090d5b94dbf7107cbbf583bc4bdd868db60e6/Directory.Packages.props#L24-L25

**Comment by martincostello** [comment] 2024-11-14 09:23
I opened a PR to my OpenAPI implementation comparison repo to us the new preview, and don't get the restore error, but it doesn't compile because of the breaking changes made to Microsoft.OpenApi v2: https://github.com/martincostello/aspnetcore-openapi/pull/148

That repo though, as you can see here [uses .NET 9](https://github.com/martincostello/aspnetcore-openapi/blob/2a0dd70ab2c7e17b3ef027da7ba0ad6e5473071d/src/TodoApp/TodoApp.csproj#L12) and uses [Swashbuckle.AspNetCore 7.0.0](https://github.com/martincostello/aspnetcore-openapi/blob/2a0dd70ab2c7e17b3ef027da7ba0ad6e5473071d/src/TodoApp/TodoApp.csproj#L23-L24).

Given that, I'm fairly sure the issue is related to something in your local project setup (wildcard versions?) rather than a generic inability to use this project with .NET 9.

If the above isn't the issue, then we'll need a fully-reproducible example to look at - a screenshot of something in Visual Studio isn't sufficient.

**Comment by raffaeler** [comment] 2024-11-14 09:27
Thank you for the prompt response @martincostello 
The dependency on the preview that you rightly reported was a further test, but the initial outcome does not change if you don't reference it directly.

I understand you need a repro but I am currently unable to do it until the weekend.

**Comment by raffaeler** [comment] 2024-11-14 09:50
For your curiosity, after reversing to the .NET RC, I went to nuget and updated all the references. This time I did not reference that dll directly.
This is the result:

![image](https://github.com/user-attachments/assets/e45cd40d-56ad-4125-b39f-4459c0fb62aa)

I'll create a repro starting from scratch, but the upgrade scenario is more difficult to repro.
FYI this project is nothing special, just hoting a bunch of webapi. The only relevant reference is Semantic Kernel that I plan to get rid of, due to its limitations.

**Comment by martincostello** [comment] 2024-11-14 09:58
Looks like the issue stems from whatever is bringing in this dependency: [Microsoft.OpenApi.ApiManifest@0.5.4-preview](https://www.nuget.org/packages/Microsoft.OpenApi.ApiManifest/0.5.4-preview#dependencies-body-tab)

It explicitly forbids System.Text.Json 9+:

![image](https://github.com/user-attachments/assets/d7683af1-e8ad-4b1d-aad5-8fcdf0cbf022)

Looks like that comes from [here](https://github.com/microsoft/OpenApi.ApiManifest/blob/a515b338bbf765f9ad5bf3248d6cbb167bd51f07/src/lib/apimanifest.csproj#L38).

I suggest opening an issue (or PR) in that repo and getting them to relax/remove that restriction.

**Comment by martincostello** [comment] 2024-11-14 10:00
In fact, there already is an issue: https://github.com/microsoft/OpenApi.ApiManifest/issues/116

**Comment by martincostello** [comment] 2024-11-14 10:01
Closing this as external.

**Closed by martincostello** 2024-11-14 10:01 UTC
Labels: upstream-openapi-dotnet

**Comment by raffaeler** [comment] 2024-11-14 10:04
Thank you!
