### ISSUE TITLE
Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsParameterFilter exception in combination with .NET8

### ISSUE THREAD

**Issue by plewam** [domaindrivendev/Swashbuckle.AspNetCore#2737] opened 2023-11-17 10:53 UTC
Hi All,

with the release of .NET8 this week I tried to upgrade my restApi. I use `Swashbuckle.AspNetCore` with version `6.5.0`. Once I make a request towards my API I get the below exception resulting in a code 500. When remaining at .NET7 I do not encounter this problem.

Any help would be highly appreciated.

I add my SwaggerGen as below:

```
builder.Services.AddSwaggerGen(o =>
{
    ConfigureSwaggerGenOptions(o);
    o.DocumentFilter<CustomModelDocumentFilter>();
});
```

And add my Swagger endpoints like this:

```
if (app.Environment.IsDevelopment() || app.Environment.IsProduction())
{
    app.UseSwagger();
    app.UseSwaggerUI(o =>
    {
        foreach (var description in apiVersionDescriptionProvider.ApiVersionDescriptions)
        {
            o.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json",
                $"My.App.Namespace - {description.GroupName.ToUpper()}");
        }

        o.RoutePrefix = string.Empty;
    });
}
```

```
[ERR] Connection id ""0HMV7B63OMRU5"", Request id ""0HMV7B63OMRU5:00000001"": An unhandled exception was thrown by the application. System.InvalidOperationException: A suitable constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsParameterFilter' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type , Type[], ConstructorInfo& , Nullable`1[]& )
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider, Type , Object[] )
   at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.CreateFilter[TFilter](FilterDescriptor)
   at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.<>c__DisplayClass4_0.<Configure>b__0(FilterDescriptor filterDescriptor)
   at System.Collections.Generic.List`1.ForEach(Action`1)
   at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.Configure(SwaggerGeneratorOptions)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.SwaggerGenServiceCollectionExtensions.<>c.<AddSwaggerGen>b__0_1(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type)
   at lambda_method1(Closure, Object, HttpContext, IServiceProvider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.<>c__DisplayClass6_0.<CreateMiddleware>b__0(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1)
```

**Comment by abeven** [comment] 2023-12-15 19:09
Just ran into this same issue - how did you resolve?

**Comment by plewam** [comment] 2023-12-16 12:12
@abeven Sadly I didn't. I remained at NET7 where the issue does not exist. I am quite sure an update is needed for this library.

**Comment by soroshsabz** [comment] 2024-01-18 23:55
ITNOA

@domaindrivendev Any update?

**Comment by Havunen** [comment] 2024-02-17 15:58
This might be fixed in DotSwashbuckle, can you test using it please.
https://github.com/Havunen/DotSwashbuckle
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

**Comment by plewam** [comment] 2024-02-23 13:05
@Havunen Works like a charm thanks :) Just moved to your new library

**Comment by willhuo** [comment] 2024-03-22 06:49
come across the same issue
it would bu ok when publish without Trim self-contained deployments and executables

**Comment by martincostello** [comment] 2024-04-14 08:32
Closing as a duplicate of #2747 (though I realise you reported it first).

Sounds like us adding `net8.0` will likely fix this.

**Closed by martincostello** 2024-04-14 08:32 UTC
