### ISSUE TITLE
StringEnumConverter is not respected when inherited class is used

### ISSUE THREAD

**Issue by fabicz** [domaindrivendev/Swashbuckle.AspNetCore#2474] opened 2022-08-02 23:18 UTC
Swashbuckle.AspNetCore.Newtonsoft 6.4.0

Code to reproduce:
```cs
    [JsonConverter(typeof(StringOnlyEnumConverter))]
    public enum PromotionType
    {
        New,
        Paying,
    }

    public class StringOnlyEnumConverter : Newtonsoft.Json.Converters.StringEnumConverter
    {
        public StringOnlyEnumConverter()
        {
            AllowIntegerValues = false;
        }
    }
```

output is
```
    "PromotionType": {
      "format": "int32",
      "enum": [
        0,
        1
      ],
      "type": "integer"
    },
```

while using
```cs
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum PromotionType
    {
        New,
        Paying,
    }
```

will produce
```
    "PromotionType": {
      "enum": [
        "New",
        "Paying"
      ],
      "type": "string"
    },
```

Might be related to #2475

**Comment by icnocop** [comment] 2022-09-20 17:17
Are you calling `services.AddSwaggerGenNewtonsoftSupport();`?

Are you registering the converters?
```
 .AddJsonOptions(options =>
 {
     options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
 })
 .AddNewtonsoftJson(options =>
 {
     options.SerializerSettings.Converters.Add(new StringOnlyEnumConverter());
 })
```

Does it work if you call `services.AddSwaggerGen(c => {c.DescribeAllEnumsAsStrings(); } );`?

**Comment by fabicz** [comment] 2022-09-20 19:21
@icnocop 

> Are you calling `services.AddSwaggerGenNewtonsoftSupport();`?

Yes, other JSON configurations work just fine (like JsonProperty attribute with custom naming)

> Are you registering the converters?

Nope, that's not intended. We don't want to enable such converter by default, only for certain cases. 

> Does it work if you call `services.AddSwaggerGen(c => {c.DescribeAllEnumsAsStrings(); } );`?

I guess it would, but same as above, that's not intended, we want to follow case by case basis. I can try if you insist.

**Comment by nzdjigit** [comment] 2023-02-06 00:24
Yeah, I agree. I think this should be fixed. We should be able to control the enum behaviour at the individual property level by decorating it with the `[JsonConverter(typeof(JsonStringEnumConverter))]` attribute rather than making it global. So far I can see only two options of doing this:

1. `builder.Services.AddControllers()
                .AddJsonOptions(options => { options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()); });`
2. Or decorating the enum declaration with `[JsonConverter(typeof(JsonStringEnumConverter))]`

Both of these options will have a global effect. It would be ideal to be able to control that at an individual property declaration level in the DTOs.

**Comment by jgarciadelanoceda** [comment] 2024-06-01 19:31
Hi @fabicz , I have not been able to reproduce this behaviour.
Neither with 6.4.0 version or latest bits.

Did you add the AddSwaggerGenNewtonsoftSupport?, because you could be using the System.Text.Json serializer, as it's the default.

@martincostello  this is a candidate issue to close

**Closed** 2024-09-30 08:54 UTC
