### ISSUE TITLE
Nullability with using [FromForm] on a class doesn't work

### ISSUE THREAD

**Issue by quails4Eva** [domaindrivendev/Swashbuckle.AspNetCore#2157] opened 2021-07-05 08:56 UTC
V6.1.4

When using the [FromForm] attribute for a class parameter, it doesn't seem to correctly apply nullable attributes to the properties e.g. `[FromForm] MyClass myObj` . Though if you pass an array it does seem to do it correctly (as it uses a reference to the definition) `[FromForm] MyClass[] myObjs`. Though in this case using an IFormFile property on the array didn't seem to work.

**Comment by John-Paul-R** [comment] 2021-10-01 15:51
Can confirm this is happening. Optional props on a param marked with `[FromForm]` are correctly excluded in the "required" array in the generated swagger doc, but are not marked with `nullable: true`.

This causes downstream problems with interpreting the generated swagger doc. (Things like NSwag will treat the props as non-nullable.)

## Example:

Here is an example of a controller method and a mock of the generated swagger doc, along with the
expected swagger doc. If you feel it is necessary, I can see about creating a small repo to reproduce, though I think this illustrates the issue fairly clearly.

It is worth noting that the props of this `ExampleItemCreateRequest` are correctly marked as nullable elsewhere in the swagger doc. It is only when it is used for `multipart/form-data` that prop nullability is not respected.

### C# Controller

```csharp
// Request Data Obj
public class ExampleItemCreateRequest
{
	// This is correctly required and non-nullable.
	[Required]
	public string Name { get; set; } = null!;

	// This should be nullable in the generated swagger doc, but is not.
	// It is not explicitly required, however.
	public string? Description { get; set; }
}
```

```csharp
// Controller
[HttpPost]
public async Task<ActionResult> CreateExampleItem([FromForm] ExampleItemCreateRequest request)
{
	// Process request
}
```

### Generated Swagger

```json
"requestBody": {
  "content": {
    "multipart/form-data": {
	  "schema": {
	    "required": [
		  "Name"
		],
		"type": "object",
		"properties": {
		  "Name": {
			"type": "string"
		  },
		  "Description": {
			"type": "string"
		  }
		},
		"encoding": {
		  "Title": {
			"style": "form"
		  },
		  "Description": {
			"style": "form"
		  }
		}
	  }
	}
  }
}
```

### Expected Swagger

```jsonc
"requestBody": {
  "content": {
    "multipart/form-data": {
	  "schema": {
	    "required": [
		  "Name"
		],
		"type": "object",
		"properties": {
		  "Name": {
			"type": "string"
		  },
		  "Description": {
			"type": "string",
			"nullable": true // This should be nullable
		  }
		},
		"encoding": {
		  "Title": {
			"style": "form"
		  },
		  "Description": {
			"style": "form"
		  }
		}
	  }
	}
  }
}
```

**Comment by John-Paul-R** [comment] 2021-10-04 16:55
For those who come after me, an OperationFilter to patch this problem:

```csharp
public class OptionalFormDataFilter : IOperationFilter
{
	public void Apply(OpenApiOperation operation, OperationFilterContext context)
	{
		if (operation.RequestBody?.Content.ContainsKey("multipart/form-data") ?? false) {
			foreach (var content in operation.RequestBody.Content) {
				var requiredProps = content.Value.Schema.Required;
				var props = content.Value.Schema.Properties;
				foreach (var prop in props) {
					if (!requiredProps.Contains(prop.Key)) {
						prop.Value.Nullable = true;
					}
				}
			}

		}
	}
}
```

**Comment by berhir** [comment] 2022-01-12 15:43
We updated to .NET 6 and the latest version of Swashbuckle and now we are having this issue in multiple places.

I looked at the code and the bug was introduced with this commit 05432a930dde38b3f1d9d667fba5d6861f1ffbae ("Only apply nullable, readOnly, writeOnly to Schema properties").
At least the nullable information must be applied to models used with `[FromForm]` too.
@domaindrivendev can you revert this change partially to fix the issue?

**Comment by berhir** [comment] 2022-01-12 22:28
@John-Paul-R Thanks for sharing your solution. I modified it slightly, because in our case, not all fields without a required attribute are nullable.

```cs
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Linq;

namespace TruckerApp.Web.Common.Swagger
{
    public class SwaggerOptionalFormDataFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            if (operation.RequestBody?.Content.ContainsKey("multipart/form-data") ?? false)
            {
                foreach (var content in operation.RequestBody.Content)
                {
                    var requiredProps = content.Value.Schema.Required;
                    var props = content.Value.Schema.Properties;
                    foreach (var prop in props)
                    {
                        var paramterDescription = context.ApiDescription.ParameterDescriptions.FirstOrDefault(paramDesc => paramDesc.Name == prop.Key);
                        if (!requiredProps.Contains(prop.Key) && paramterDescription != null && paramterDescription.Type.IsReferenceOrNullableType())
                        {
                            prop.Value.Nullable = true;
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by martincostello** [comment] 2024-04-14 10:16
To make issue tracking a bit less overwhelming for the new maintainers (see #2778), I've created a new tracking issue to roll-up various nullability issues here: #2793.

We'll refer back to this issue from there and include it as part of resolving that issue, but I'm going to close this one to help prune the backlog.

**Closed by martincostello** 2024-04-14 10:16 UTC
